export const GLOSSARY = [
  // Vitres et verre
  { slug: "vitre-thermos", term: "Vitre thermos", aka: ["thermos", "unite scellee", "verre thermos", "fenetre thermos"], definition: "Unite de verre composee de deux ou trois panneaux separes par un espaceur hermetique et remplis de gaz argon ou air sec. Le thermos assure l'isolation thermique et acoustique de vos fenetres.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-embuee", pricingSlug: "remplacement-thermos" },
  { slug: "verre-low-e", term: "Verre Low-E", aka: ["low-e", "basse emissivite", "low emissivity"], definition: "Verre recouvert d'un enduit microscopique d'oxydes metalliques qui reflechit la chaleur infrarouge. Il garde la chaleur a l'interieur en hiver et la bloque en ete, ameliorant l'efficacite energetique de 30 a 40%.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-froide-au-toucher", pricingSlug: "remplacement-thermos" },
  { slug: "gaz-argon", term: "Gaz argon", aka: ["argon"], definition: "Gaz inerte injecte entre les panneaux d'un thermos pour ameliorer l'isolation thermique. L'argon est 34% plus dense que l'air, ce qui ralentit les transferts de chaleur par convection. Quand l'argon s'echappe, le thermos perd son pouvoir isolant.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-froide-au-toucher", pricingSlug: "remplacement-thermos" },
  { slug: "espaceur", term: "Espaceur (intercalaire)", aka: ["intercalaire", "spacer", "warm edge"], definition: "Piece en aluminium ou en materiau composite qui separe les deux vitres d'un thermos et maintient l'ecart uniforme. Les espaceurs 'warm edge' modernes reduisent les ponts thermiques au pourtour du verre.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: "condensation-entre-vitres", pricingSlug: "remplacement-thermos" },
  { slug: "double-vitrage", term: "Double vitrage", aka: ["double panneau", "verre double"], definition: "Fenetre composee de deux panneaux de verre separes par un espace rempli d'air ou de gaz argon. C'est le standard au Quebec depuis les annees 1980. Les modeles plus anciens sans gaz argon ni verre Low-E sont beaucoup moins performants.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: "double-vitrage-brise", pricingSlug: "remplacement-thermos" },
  { slug: "triple-vitrage", term: "Triple vitrage", aka: ["triple panneau", "verre triple"], definition: "Fenetre a trois panneaux de verre avec deux espaces remplis de gaz argon. Offre une isolation superieure au double vitrage, ideale pour les facades exposees au nord ou les regions tres froides du Quebec.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: null, pricingSlug: "remplacement-thermos" },
  { slug: "desembuage", term: "Desembuage", aka: ["defogging"], definition: "Procede qui consiste a percer de petits trous dans le thermos pour evacuer l'humidite emprisonnee entre les vitres, puis a sceller les trous. Solution temporaire (3-5 ans) moins couteuse que le remplacement complet du thermos.", category: "verre", serviceSlug: "desembuage", problemSlug: "vitre-thermos-embuee", pricingSlug: "desembuage" },
  { slug: "verre-trempe", term: "Verre trempe", aka: ["tempered glass"], definition: "Verre chauffe puis refroidi rapidement pour le rendre 4 a 5 fois plus resistant qu'un verre ordinaire. Quand il casse, il se fragmente en petits morceaux non coupants. Obligatoire pres des portes et dans certaines zones a risque.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: null, pricingSlug: "remplacement-thermos" },

  // Quincaillerie
  { slug: "quincaillerie-fenetre", term: "Quincaillerie de fenetre", aka: ["hardware", "pieces de fenetre"], definition: "Ensemble des pieces mecaniques d'une fenetre : poignees, loquets, charnieres, manivelles, cames de verrouillage, ressorts. La quincaillerie s'use avec le temps et peut etre remplacee individuellement sans changer la fenetre.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-difficile-ouvrir", pricingSlug: "reparation-porte-patio" },
  { slug: "roulette-porte-patio", term: "Roulette de porte-patio", aka: ["rouleau", "galet", "roue porte patio"], definition: "Pieces montees sous la porte-patio qui lui permettent de glisser sur le rail. Les roulettes s'usent apres 10-15 ans et causent une porte qui coince ou glisse difficilement. C'est la reparation la plus courante et la plus efficace.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "porte-patio-coince", pricingSlug: "reparation-porte-patio" },
  { slug: "manivelle-fenetre", term: "Manivelle de fenetre", aka: ["crank operator", "operateur a manivelle"], definition: "Mecanisme a engrenage utilise pour ouvrir et fermer les fenetres a battant et a auvent. La manivelle tourne un bras qui pousse la fenetre vers l'exterieur. Piece d'usure courante, facilement remplacable.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "manivelle-fenetre-cassee", pricingSlug: "reparation-porte-patio" },
  { slug: "came-verrouillage", term: "Came de verrouillage", aka: ["cam lock", "came", "loquet"], definition: "Piece en forme d'excentrile qui, en tournant, tire la fenetre vers le cadre pour assurer l'etancheite. Quand la came est usee ou desajustee, la fenetre ne ferme plus hermetiquement et laisse passer l'air.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-qui-ferme-mal", pricingSlug: "reparation-porte-patio" },
  { slug: "gache", term: "Gache", aka: ["striker plate", "platine de gache"], definition: "Piece metallique fixee au cadre dans laquelle s'engage le pene ou la came de verrouillage. Si la gache est mal alignee, la fenetre ou la porte ne verrouille pas correctement.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-difficile-verrouiller", pricingSlug: "reparation-porte-patio" },
  { slug: "charniere-friction", term: "Charniere a friction", aka: ["friction hinge", "charniere fenetre battant"], definition: "Charniere speciale pour fenetres a battant qui maintient la fenetre ouverte a n'importe quel angle grace a la friction. Avec le temps, la friction diminue et la fenetre ne reste plus ouverte.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "charniere-fenetre-cassee", pricingSlug: "reparation-porte-patio" },

  // Étanchéité
  { slug: "coupe-froid", term: "Coupe-froid", aka: ["weatherstrip", "weatherstripping", "joint d'etancheite"], definition: "Joint souple installe sur le cadre d'une fenetre ou d'une porte qui assure l'etancheite a l'air quand l'ouverture est fermee. Se presente sous forme de mousse, de caoutchouc, de silicone ou de brosse. Dure 5 a 10 ans.", category: "etancheite", serviceSlug: "coupe-froid", problemSlug: "coupe-froid-use", pricingSlug: "coupe-froid" },
  { slug: "calfeutrage", term: "Calfeutrage", aka: ["caulking", "scellant", "sealant"], definition: "Application d'un scellant souple (silicone, polyurethane, acrylique) autour du cadre d'une fenetre ou d'une porte pour empecher les infiltrations d'air et d'eau. Le calfeutrage exterieur doit etre refait tous les 5 a 7 ans au Quebec.", category: "etancheite", serviceSlug: "calfeutrage", problemSlug: "calfeutrage-fenetre-craque", pricingSlug: "calfeutrage-fenetres" },
  { slug: "coupe-bise", term: "Coupe-bise (bas de porte)", aka: ["door sweep", "bas de porte"], definition: "Joint installe au bas d'une porte pour empecher l'air froid de passer entre la porte et le seuil. Essentiel au Quebec pour l'efficacite energetique. Se remplace facilement.", category: "etancheite", serviceSlug: "coupe-froid", problemSlug: "courant-air-fenetre", pricingSlug: "coupe-froid" },
  { slug: "solin", term: "Solin", aka: ["flashing", "larmier"], definition: "Piece de metal (aluminium ou acier galvanise) installee au-dessus d'une fenetre ou d'une porte pour devier l'eau de pluie et empecher les infiltrations. Un solin manquant ou mal installe est une cause frequente d'infiltration d'eau.", category: "etancheite", serviceSlug: "calfeutrage", problemSlug: "infiltration-eau-fenetre", pricingSlug: "calfeutrage-fenetres" },

  // Types de fenêtres
  { slug: "fenetre-battant", term: "Fenetre a battant", aka: ["casement window", "fenetre a manivelle"], definition: "Fenetre articulee sur le cote qui s'ouvre vers l'exterieur a l'aide d'une manivelle. Tres populaire au Quebec pour son excellente etancheite a l'air. La manivelle et les charnieres sont les pieces d'usure principales.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: "manivelle-fenetre-cassee", pricingSlug: "reparation-porte-patio" },
  { slug: "fenetre-guillotine", term: "Fenetre a guillotine", aka: ["double hung window", "fenetre coulissante verticale"], definition: "Fenetre dont le panneau du bas glisse vers le haut pour ouvrir. Tres courante dans les triplex et duplex montrealais. Les ressorts de balancement s'usent avec le temps, rendant la fenetre difficile a maintenir ouverte.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-guillotine-bloquee", pricingSlug: "reparation-porte-patio" },
  { slug: "fenetre-coulissante", term: "Fenetre coulissante", aka: ["sliding window", "fenetre horizontale"], definition: "Fenetre dont un ou deux panneaux glissent horizontalement sur des rails. Simple et economique, elle est courante dans les maisons de banlieue. Les rails et roulettes s'usent et peuvent etre remplaces.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-coulissante-bloquee", pricingSlug: "reparation-porte-patio" },
  { slug: "fenetre-auvent", term: "Fenetre a auvent", aka: ["awning window"], definition: "Fenetre articulee en haut qui s'ouvre vers l'exterieur par le bas. Peut rester ouverte meme sous la pluie legere. Utilise le meme type de manivelle que la fenetre a battant.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: "manivelle-fenetre-cassee", pricingSlug: "reparation-porte-patio" },
  { slug: "fenetre-fixe", term: "Fenetre fixe", aka: ["fixed window", "fenetre panoramique"], definition: "Fenetre qui ne s'ouvre pas, installee uniquement pour la lumiere et la vue. N'a aucune quincaillerie mobile. Le seul probleme possible est le thermos qui s'embue ou se brise.", category: "fenetres", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-embuee", pricingSlug: "remplacement-thermos" },
  { slug: "porte-patio", term: "Porte-patio (porte coulissante)", aka: ["patio door", "porte coulissante", "sliding door"], definition: "Grande porte vitree dont un panneau glisse sur un rail. La porte-patio est sujette a l'usure des roulettes, des poignees et des serrures. La plupart des problemes se reglent sans remplacer la porte complete.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: "porte-patio-coince", pricingSlug: "reparation-porte-patio" },

  // Insertion
  { slug: "insertion-porte", term: "Insertion de porte", aka: ["door insert", "vitrage de porte", "door glass insert"], definition: "Panneau vitre decoratif qui s'insere dans une porte d'entree. Disponible en verre clair, givre, texture ou avec des motifs decoratifs en fer forge. Peut etre remplace sans changer la porte complete.", category: "insertion", serviceSlug: "insertion-porte", problemSlug: "insertion-porte-embuee", pricingSlug: "insertion-porte" },

  // Moustiquaires
  { slug: "moustiquaire", term: "Moustiquaire", aka: ["screen", "fly screen", "window screen"], definition: "Cadre muni d'une toile fine qui s'installe dans l'ouverture d'une fenetre ou d'une porte pour laisser passer l'air tout en bloquant les insectes. Disponible en fibre de verre (standard), aluminium ou pet screen (resistant aux animaux).", category: "moustiquaire", serviceSlug: "moustiquaires-sur-mesure", problemSlug: "moustiquaire-dechiree", pricingSlug: "moustiquaires" },
  { slug: "pet-screen", term: "Pet screen (toile anti-animaux)", aka: ["toile pour animaux", "moustiquaire resistant animaux"], definition: "Toile de moustiquaire 7 fois plus resistante que la fibre de verre standard, concue pour resister aux griffes de chats et de chiens. Un peu plus couteuse mais essentielle si vous avez des animaux domestiques.", category: "moustiquaire", serviceSlug: "moustiquaires-sur-mesure", problemSlug: "moustiquaire-dechiree", pricingSlug: "moustiquaires" },

  // Efficacité énergétique
  { slug: "cote-energy-star", term: "Cote Energy Star", aka: ["energy star", "energuide"], definition: "Programme de certification qui identifie les fenetres les plus efficaces energetiquement. Au Quebec, les fenetres Energy Star zone climatique 3 sont recommandees. Le remplacement du thermos par un modele Low-E avec argon ameliore significativement la performance.", category: "energie", serviceSlug: "remplacement-vitre-thermos", problemSlug: "facture-chauffage-elevee", pricingSlug: "remplacement-thermos" },
  { slug: "coefficient-u", term: "Coefficient U (facteur U)", aka: ["u-factor", "u-value", "valeur U"], definition: "Mesure de la capacite d'une fenetre a laisser passer la chaleur. Plus le coefficient U est bas, meilleure est l'isolation. Un bon thermos moderne au Quebec a un coefficient U de 1.4 ou moins.", category: "energie", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-froide-au-toucher", pricingSlug: "remplacement-thermos" },
  { slug: "coefficient-r", term: "Valeur R", aka: ["r-value", "resistance thermique"], definition: "Inverse du coefficient U, la valeur R mesure la resistance au passage de la chaleur. Plus la valeur R est elevee, meilleure est l'isolation. Une fenetre a double vitrage avec argon et Low-E a une valeur R d'environ 3 a 4.", category: "energie", serviceSlug: "remplacement-vitre-thermos", problemSlug: "facture-chauffage-elevee", pricingSlug: "remplacement-thermos" },
  { slug: "pont-thermique", term: "Pont thermique", aka: ["thermal bridge", "thermal bridging"], definition: "Zone d'une fenetre ou la chaleur s'echappe plus facilement, typiquement au pourtour du verre ou le cadre rejoint le mur. Les espaceurs 'warm edge' modernes et un bon calfeutrage reduisent les ponts thermiques.", category: "energie", serviceSlug: "calfeutrage", problemSlug: "fenetre-froide-au-toucher", pricingSlug: "calfeutrage-fenetres" },

  // Bois
  { slug: "epoxy-bois", term: "Reparation a l'epoxy (bois)", aka: ["wood epoxy", "pate a bois epoxy"], definition: "Technique de reparation qui utilise une resine epoxy pour combler et durcir le bois pourri sans avoir a remplacer toute la piece. Ideal pour les reparations localisees de cadres de fenetres et bas de portes.", category: "bois", serviceSlug: "reparation-portes-bois", problemSlug: "cadre-fenetre-pourri", pricingSlug: "reparation-portes-bois" },
  { slug: "greffe-bois", term: "Greffe de bois", aka: ["wood splicing", "dutchman repair"], definition: "Technique de restauration qui consiste a retirer la section de bois pourri et a la remplacer par un morceau de bois neuf colle et ajuste parfaitement. Utilise pour les dommages plus etendus que ce que l'epoxy peut reparer.", category: "bois", serviceSlug: "reparation-portes-bois", problemSlug: "porte-bois-pourri-bas", pricingSlug: "reparation-portes-bois" },

  // Programme
  { slug: "opti-fenetre", term: "Programme OPTI-FENETRE", aka: ["opti-fenetre", "remise a neuf", "reconditionnement"], definition: "Programme exclusif Vosthermos qui regroupe tous les services de reparation (thermos, quincaillerie, coupe-froid, calfeutrage, moustiquaires) en un forfait cle en main. Permet d'economiser jusqu'a 70% par rapport au remplacement complet des fenetres.", category: "programme", serviceSlug: null, problemSlug: "facture-chauffage-elevee", pricingSlug: null },

  // Réglementation
  { slug: "rbq", term: "RBQ (Regie du batiment du Quebec)", aka: ["regie du batiment", "licence RBQ"], definition: "Organisme gouvernemental qui encadre les travaux de construction et de renovation au Quebec. Vosthermos detient la licence RBQ 5790-9498-01, garantissant que nos travaux respectent les normes en vigueur.", category: "reglementation", serviceSlug: null, problemSlug: null, pricingSlug: null },
  { slug: "garantie-legale", term: "Garantie legale (GCR)", aka: ["garantie construction residentielle"], definition: "Au Quebec, la Garantie de construction residentielle protege les acheteurs de maisons neuves. Pour les renovations, la garantie depend de l'entrepreneur. Vosthermos offre une service professionnel garanti sur les thermos et une garantie sur la main-d'oeuvre.", category: "reglementation", serviceSlug: null, problemSlug: null, pricingSlug: null },

  // Mesures
  { slug: "pied-carre", term: "Pied carre (pi²)", aka: ["square foot", "sq ft", "pi2"], definition: "Unite de mesure utilisee au Quebec pour calculer la surface d'un thermos de fenetre. Le prix au pied carre d'un thermos varie entre 8$ et 25$ selon le type de verre. Pour calculer: largeur (po) x hauteur (po) / 144 = pieds carres.", category: "mesures", serviceSlug: "remplacement-vitre-thermos", problemSlug: null, pricingSlug: "remplacement-thermos" },
  { slug: "pied-lineaire", term: "Pied lineaire (pi.lin.)", aka: ["linear foot", "pied linéaire"], definition: "Unite de mesure utilisee pour le calfeutrage. Le prix au pied lineaire varie entre 8$ et 20$ selon le type de scellant. On mesure le perimetre de la fenetre pour calculer la quantite necessaire.", category: "mesures", serviceSlug: "calfeutrage", problemSlug: null, pricingSlug: "calfeutrage-fenetres" },

  // Quincaillerie (suppléments)
  { slug: "balance-ressort", term: "Balance a ressort (spirale)", aka: ["spiral balance", "balance spirale", "ressort de fenetre"], definition: "Mecanisme a ressort helicoidal installe dans le cadre d'une fenetre a guillotine pour contrebalancer le poids du panneau et le maintenir ouvert. Quand la balance est usee, la fenetre ne reste plus ouverte et retombe toute seule.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: "fenetre-guillotine-bloquee", pricingSlug: "reparation-porte-patio" },
  { slug: "ferme-porte", term: "Ferme-porte", aka: ["door closer", "groom de porte"], definition: "Dispositif hydraulique fixe en haut d'une porte qui la referme automatiquement de facon controlee. Courant sur les portes d'entree et commerciales. La vitesse de fermeture et la force de verrouillage sont ajustables.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: null, pricingSlug: "reparation-porte-patio" },
  { slug: "serrure-multipoint", term: "Serrure multipoint", aka: ["multipoint lock", "serrure 3 points"], definition: "Systeme de verrouillage qui engage la porte en plusieurs points du cadre simultanement (haut, milieu, bas). Offre une securite et une etancheite superieures aux serrures a un seul point. Courant sur les portes d'entree modernes.", category: "quincaillerie", serviceSlug: "remplacement-quincaillerie", problemSlug: null, pricingSlug: "reparation-porte-patio" },

  // Verre (suppléments)
  { slug: "verre-lamine", term: "Verre lamine", aka: ["laminated glass", "verre feuillete", "verre securitaire"], definition: "Verre compose de deux panneaux colles ensemble par un film plastique intercalaire (PVB). En cas de bris, les morceaux restent colles au film au lieu de tomber. Utilise pour la securite et l'insonorisation.", category: "verre", serviceSlug: "remplacement-vitre-thermos", problemSlug: null, pricingSlug: "remplacement-thermos" },
  { slug: "gain-solaire", term: "Coefficient de gain solaire (CGCS)", aka: ["SHGC", "solar heat gain coefficient", "facteur solaire"], definition: "Mesure de la quantite d'energie solaire qui traverse une fenetre. Un CGCS bas (0.25) bloque la chaleur du soleil en ete, tandis qu'un CGCS eleve (0.50+) laisse entrer la chaleur gratuite en hiver. Le choix depend de l'orientation de la fenetre.", category: "energie", serviceSlug: "remplacement-vitre-thermos", problemSlug: null, pricingSlug: "remplacement-thermos" },

  // Étanchéité (suppléments)
  { slug: "mousse-expansive", term: "Mousse expansive (mousse isolante)", aka: ["expanding foam", "mousse polyurethane", "great stuff"], definition: "Mousse isolante en aerosol qui gonfle en sechant pour combler les espaces entre le cadre de la fenetre et la structure du mur. Essentielle pour eliminer les ponts thermiques au pourtour des ouvertures.", category: "etancheite", serviceSlug: "calfeutrage", problemSlug: "courant-air-fenetre", pricingSlug: "calfeutrage-fenetres" },
  { slug: "condensation-fenetre", term: "Condensation sur les fenetres", aka: ["window condensation", "buee fenetre"], definition: "Formation de gouttelettes d'eau sur la surface interieure ou exterieure d'une vitre. La condensation interieure indique un taux d'humidite trop eleve ou une fenetre mal isolee. La condensation entre les vitres signale un thermos defectueux a remplacer.", category: "etancheite", serviceSlug: "remplacement-vitre-thermos", problemSlug: "fenetre-embuee", pricingSlug: "remplacement-thermos" },

  // Types de fenêtres (suppléments)
  { slug: "fenetre-oscillo-battant", term: "Fenetre oscillo-battant", aka: ["tilt and turn window", "fenetre basculante"], definition: "Fenetre europeenne a double mode d'ouverture : elle bascule vers l'interieur par le haut pour la ventilation, ou s'ouvre completement comme un battant lateral. Populaire dans les constructions recentes pour sa polyvalence et son etancheite superieure.", category: "fenetres", serviceSlug: "remplacement-quincaillerie", problemSlug: null, pricingSlug: "reparation-porte-patio" },
];

export const GLOSSARY_CATEGORIES = [
  { slug: "verre", label: "Vitres et verres", icon: "fas fa-snowflake" },
  { slug: "quincaillerie", label: "Quincaillerie", icon: "fas fa-cogs" },
  { slug: "etancheite", label: "Etancheite", icon: "fas fa-wind" },
  { slug: "fenetres", label: "Types de fenetres", icon: "fas fa-th-large" },
  { slug: "insertion", label: "Insertions", icon: "fas fa-door-closed" },
  { slug: "moustiquaire", label: "Moustiquaires", icon: "fas fa-border-all" },
  { slug: "energie", label: "Efficacite energetique", icon: "fas fa-bolt" },
  { slug: "bois", label: "Reparation bois", icon: "fas fa-tree" },
  { slug: "programme", label: "Programmes", icon: "fas fa-star" },
  { slug: "reglementation", label: "Reglementation", icon: "fas fa-gavel" },
  { slug: "mesures", label: "Mesures et calculs", icon: "fas fa-ruler" },
];

export function getGlossaryTerm(slug) {
  return GLOSSARY.find((g) => g.slug === slug);
}
