export const PRICING = [
  {
    slug: "remplacement-thermos",
    serviceSlug: "remplacement-vitre-thermos",
    title: "Remplacement de vitre thermos",
    metaTitle: "Prix remplacement vitre thermos 2026 | Combien ca coute | Vosthermos",
    metaDescription: "Combien coute le remplacement d'une vitre thermos au Quebec en 2026? Prix au pied carre, grille tarifaire, facteurs qui influencent le prix. Soumission gratuite 514-825-8411.",
    heroSubtitle: "Le remplacement de thermos coute entre 150$ et 400$ par unite, soit 60 a 70% moins cher que le remplacement complet de la fenetre.",
    priceRange: { min: 150, max: 400, unit: "par unite installee" },
    pricePerSqFt: { min: 15, max: 30, label: "par pied carre" },
    tableRows: [
      { item: "Thermos standard (24\" x 36\")", price: "150$ - 200$" },
      { item: "Thermos moyen (36\" x 48\")", price: "200$ - 300$" },
      { item: "Thermos grande dimension (48\" x 60\"+)", price: "300$ - 400$" },
      { item: "Thermos Low-E avec argon", price: "+30$ a +60$ par unite" },
      { item: "Thermos triple vitrage", price: "+80$ a +120$ par unite" },
      { item: "Thermos forme speciale (arrondi, trapeze)", price: "Sur estimation" },
    ],
    factors: [
      { title: "Dimension de la vitre", desc: "Plus le thermos est grand, plus le prix augmente. Le calcul se fait au pied carre." },
      { title: "Type de verre", desc: "Le verre Low-E avec gaz argon offre une meilleure isolation mais coute un peu plus cher. C'est le standard recommande." },
      { title: "Nombre d'unites", desc: "Plus vous remplacez de thermos en meme temps, meilleur sera le prix unitaire. Le programme OPTI-FENETRE offre un forfait avantageux." },
      { title: "Accessibilite", desc: "Les fenetres en hauteur ou difficiles d'acces peuvent necessiter de l'equipement supplementaire." },
      { title: "Urgence", desc: "Un service regulier vs un remplacement d'urgence peut influencer la tarification." },
    ],
    comparison: {
      title: "Remplacement thermos vs fenetre complete",
      rows: [
        { label: "Prix moyen (fenetre standard)", thermos: "200$ - 300$", complet: "800$ - 1 500$" },
        { label: "Delai d'installation", thermos: "1-2 heures", complet: "4-8 semaines" },
        { label: "Garantie", thermos: "10 ans", complet: "Variable" },
        { label: "Debris et travaux", thermos: "Aucun", complet: "Importants" },
        { label: "Resultat isolation", thermos: "Equivalent", complet: "Equivalent" },
      ],
    },
    faq: [
      { q: "Le thermos inclut-il l'installation?", a: "Oui, tous nos prix incluent la fabrication sur mesure, le deplacement et l'installation professionnelle." },
      { q: "Est-ce que ca vaut la peine vs remplacer la fenetre?", a: "Le remplacement du thermos coute 60 a 70% moins cher qu'une fenetre neuve, avec un resultat d'isolation equivalent. Si le cadre est en bon etat, c'est la meilleure option." },
      { q: "Combien de temps dure un nouveau thermos?", a: "Un thermos de qualite dure entre 15 et 25 ans. Nos thermos sont fabriques au Quebec et garantis 10 ans." },
      { q: "Y a-t-il un minimum de commande?", a: "Non, nous remplacons un seul thermos comme 50. Cependant, regrouper plusieurs remplacements permet d'economiser sur le deplacement." },
    ],
    savings: "Economie moyenne de 800$ a 1 200$ par fenetre vs le remplacement complet",
  },
  {
    slug: "reparation-porte-patio",
    serviceSlug: "remplacement-quincaillerie",
    title: "Reparation de porte-patio",
    metaTitle: "Prix reparation porte-patio 2026 | Roulettes, serrure, poignee | Vosthermos",
    metaDescription: "Combien coute la reparation d'une porte-patio au Quebec? Prix roulettes, serrure, poignee, rail. Grille tarifaire 2026. Soumission gratuite 514-825-8411.",
    heroSubtitle: "La plupart des reparations de porte-patio coutent entre 75$ et 300$. Bien moins cher que de remplacer la porte complete (2 000$ a 5 000$).",
    priceRange: { min: 75, max: 300, unit: "selon la reparation" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Remplacement de roulettes (paire)", price: "75$ - 175$" },
      { item: "Remplacement de poignee", price: "30$ - 120$" },
      { item: "Remplacement de serrure/cylindre", price: "75$ - 250$" },
      { item: "Ajustement et nettoyage du rail", price: "50$ - 100$" },
      { item: "Remplacement du loquet de securite", price: "40$ - 100$" },
      { item: "Reparation complete (roulettes + poignee + ajustement)", price: "200$ - 350$" },
    ],
    factors: [
      { title: "Type de reparation", desc: "Un simple remplacement de poignee est beaucoup moins cher qu'une refection complete avec roulettes et serrure." },
      { title: "Marque et modele", desc: "Certaines marques utilisent des pieces proprietaires plus couteuses. Nous avons plus de 700 pieces en stock." },
      { title: "Nombre de portes", desc: "Reparer plusieurs portes en meme visite reduit le cout unitaire." },
      { title: "Etat general", desc: "Si le cadre ou le thermos sont aussi endommages, le programme OPTI-FENETRE peut etre plus avantageux." },
    ],
    comparison: {
      title: "Reparation vs remplacement de porte-patio",
      rows: [
        { label: "Prix moyen", thermos: "150$ - 300$", complet: "2 000$ - 5 000$" },
        { label: "Delai", thermos: "Meme journee", complet: "4-8 semaines" },
        { label: "Debris", thermos: "Aucun", complet: "Importants" },
        { label: "Resultat fonctionnel", thermos: "Comme neuf", complet: "Neuf" },
      ],
    },
    faq: [
      { q: "Combien coute un remplacement de roulettes de porte-patio?", a: "Le remplacement d'une paire de roulettes coute entre 75$ et 175$, installation incluse. C'est la reparation la plus courante et la plus efficace." },
      { q: "Est-ce que vous avez les pieces pour ma porte-patio?", a: "Nous avons plus de 700 pieces en stock compatibles avec toutes les grandes marques: Novatech, Lepage Millwork, Fenplast, et plus." },
      { q: "Ma porte-patio est tres vieille, vaut-il mieux la remplacer?", a: "Pas necessairement. Meme une porte de 30 ans peut retrouver son fonctionnement d'origine avec des roulettes et de la quincaillerie neuves, pour 10x moins cher qu'un remplacement." },
    ],
    savings: "Economie moyenne de 2 000$ a 4 500$ vs le remplacement de la porte",
  },
  {
    slug: "calfeutrage-fenetres",
    serviceSlug: "calfeutrage",
    title: "Calfeutrage de portes et fenetres",
    metaTitle: "Prix calfeutrage fenetres et portes 2026 | Cout au pied | Vosthermos",
    metaDescription: "Combien coute le calfeutrage de fenetres au Quebec en 2026? Prix au pied lineaire, cout par fenetre, grille tarifaire. Soumission gratuite 514-825-8411.",
    heroSubtitle: "Le calfeutrage de fenetres coute entre 8$ et 20$ par pied lineaire. C'est l'un des investissements les plus rentables pour votre maison.",
    priceRange: { min: 8, max: 20, unit: "par pied lineaire" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Calfeutrage fenetre standard (retrait + application)", price: "60$ - 120$ par fenetre" },
      { item: "Calfeutrage porte d'entree", price: "80$ - 150$" },
      { item: "Calfeutrage porte-patio", price: "100$ - 180$" },
      { item: "Maison complete (10-15 fenetres + portes)", price: "800$ - 1 500$" },
      { item: "Calfeutrage interieur seulement", price: "40$ - 80$ par fenetre" },
      { item: "Scellant premium polyurethane", price: "+20% vs standard" },
    ],
    factors: [
      { title: "Nombre d'ouvertures", desc: "Plus il y a de fenetres et portes, meilleur sera le prix unitaire. Un forfait maison complete est souvent la meilleure option." },
      { title: "Etat de l'ancien calfeutrage", desc: "Le retrait de l'ancien scellant peut prendre plus ou moins de temps selon sa condition." },
      { title: "Type de scellant", desc: "Un scellant polyurethane de qualite superieure coute un peu plus mais dure beaucoup plus longtemps au Quebec." },
      { title: "Hauteur et accessibilite", desc: "Les fenetres en hauteur necessitant une echelle ou un equipement special coutent plus cher." },
    ],
    comparison: {
      title: "Cout du calfeutrage vs pertes de chauffage",
      rows: [
        { label: "Investissement (maison complete)", thermos: "800$ - 1 500$", complet: "-" },
        { label: "Economie de chauffage/an", thermos: "200$ - 400$/an", complet: "-" },
        { label: "Retour sur investissement", thermos: "2-4 ans", complet: "-" },
        { label: "Duree de vie du calfeutrage", thermos: "5-10 ans", complet: "-" },
      ],
    },
    faq: [
      { q: "A quelle frequence faut-il refaire le calfeutrage?", a: "Au Quebec, le calfeutrage exterieur devrait etre inspecte chaque annee et refait tous les 5 a 7 ans en raison de nos hivers rigoureux." },
      { q: "Est-ce que le calfeutrage reduit vraiment la facture de chauffage?", a: "Oui, un calfeutrage deficient peut representer 15 a 25% de vos pertes de chaleur. Refaire le calfeutrage se rentabilise en 2 a 4 ans." },
      { q: "Peut-on calfeutrer en hiver?", a: "Idealement, le calfeutrage se fait quand la temperature est au-dessus de 5°C. La meilleure periode au Quebec est entre mai et octobre." },
    ],
    savings: "Economie de 200$ a 400$ par annee en chauffage",
  },
  {
    slug: "coupe-froid",
    serviceSlug: "coupe-froid",
    title: "Remplacement de coupe-froid",
    metaTitle: "Prix remplacement coupe-froid fenetres 2026 | Vosthermos",
    metaDescription: "Combien coute le remplacement du coupe-froid de fenetres au Quebec? Prix par fenetre, types de coupe-froid, grille tarifaire 2026. 514-825-8411.",
    heroSubtitle: "Le remplacement de coupe-froid coute entre 30$ et 80$ par fenetre. C'est souvent la solution la plus economique pour eliminer les courants d'air.",
    priceRange: { min: 30, max: 80, unit: "par fenetre" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Coupe-froid fenetre standard", price: "30$ - 60$" },
      { item: "Coupe-froid porte-patio", price: "50$ - 100$" },
      { item: "Coupe-froid porte d'entree", price: "40$ - 80$" },
      { item: "Bas de porte (coupe-bise)", price: "30$ - 60$" },
      { item: "Maison complete (10-15 ouvertures)", price: "400$ - 800$" },
    ],
    factors: [
      { title: "Type de coupe-froid", desc: "Il existe des dizaines de profils differents. Le prix varie selon le modele specifique a votre fenetre." },
      { title: "Marque de fenetre", desc: "Certaines marques utilisent des profils proprietaires. Nous avons des centaines de modeles en stock." },
      { title: "Nombre d'ouvertures", desc: "Un forfait maison complete est plus economique qu'un remplacement fenetre par fenetre." },
    ],
    comparison: {
      title: "Coupe-froid vs remplacement de fenetre",
      rows: [
        { label: "Prix (par fenetre)", thermos: "30$ - 80$", complet: "800$ - 1 500$" },
        { label: "Temps d'installation", thermos: "30-60 minutes", complet: "4-8 semaines" },
        { label: "Reduction courants d'air", thermos: "90%+", complet: "100%" },
        { label: "Amelioration isolation", thermos: "Significative", complet: "Maximale" },
      ],
    },
    faq: [
      { q: "Comment savoir si mon coupe-froid est use?", a: "Si vous sentez de l'air froid pres de vos fenetres fermees, si le coupe-froid est ecrase, fendille ou decolle, il est temps de le remplacer." },
      { q: "Combien ca prend de temps?", a: "Le remplacement prend environ 30 a 60 minutes par fenetre. Pour une maison complete, on peut generalement tout faire en une journee." },
    ],
    savings: "Economie de 150$ a 300$ par annee en chauffage",
  },
  {
    slug: "moustiquaires",
    serviceSlug: "moustiquaires-sur-mesure",
    title: "Moustiquaires sur mesure",
    metaTitle: "Prix moustiquaires sur mesure 2026 | Fabrication et reparation | Vosthermos",
    metaDescription: "Combien coute une moustiquaire sur mesure au Quebec? Prix reparation, fabrication, remplacement de toile. Grille tarifaire 2026. 514-825-8411.",
    heroSubtitle: "Le prix d'une moustiquaire sur mesure varie entre 25$ pour une reparation de toile et 200$ pour une porte moustiquaire complete.",
    priceRange: { min: 25, max: 200, unit: "selon le type" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Remplacement de toile dans cadre existant", price: "25$ - 60$" },
      { item: "Moustiquaire de fenetre sur mesure (cadre + toile)", price: "50$ - 120$" },
      { item: "Porte moustiquaire sur mesure", price: "100$ - 200$" },
      { item: "Moustiquaire retractable", price: "150$ - 300$" },
      { item: "Toile pet screen (resistant aux animaux)", price: "+20$ a +40$" },
      { item: "Reparation cadre + toile", price: "40$ - 100$" },
    ],
    factors: [
      { title: "Type de moustiquaire", desc: "Fenetre fixe, coulissante, retractable ou porte — chaque type a un prix different." },
      { title: "Materiau de toile", desc: "Fibre de verre (standard), aluminium (plus durable), ou pet screen (resistant aux griffes d'animaux)." },
      { title: "Dimension", desc: "Les grandes dimensions coutent plus cher. Les moustiquaires de porte-patio sont plus couteuses que celles de fenetre." },
      { title: "Reparation vs neuve", desc: "Reparer la toile dans le cadre existant est toujours moins cher que de fabriquer une moustiquaire neuve." },
    ],
    comparison: null,
    faq: [
      { q: "Combien coute un retissage de moustiquaire?", a: "Le remplacement de la toile dans votre cadre existant coute entre 25$ et 60$. C'est la solution la plus economique si le cadre est en bon etat." },
      { q: "Avez-vous de la toile resistant aux animaux?", a: "Oui, nous offrons la toile pet screen qui resiste aux griffes de chats et chiens. Elle coute un peu plus mais en vaut la peine si vous avez des animaux." },
    ],
    savings: null,
  },
  {
    slug: "reparation-portes-bois",
    serviceSlug: "reparation-portes-bois",
    title: "Reparation de portes et fenetres en bois",
    metaTitle: "Prix reparation portes fenetres en bois 2026 | Restauration | Vosthermos",
    metaDescription: "Combien coute la reparation d'une porte ou fenetre en bois au Quebec? Prix restauration, rabotage, cadre pourri. Grille 2026. Soumission gratuite 514-825-8411.",
    heroSubtitle: "La reparation de portes et fenetres en bois coute entre 75$ et 600$ selon le type de travail, soit bien moins que le remplacement complet.",
    priceRange: { min: 75, max: 600, unit: "selon les travaux" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Rabotage de porte qui colle", price: "75$ - 150$" },
      { item: "Ajustement de charnieres et quincaillerie", price: "50$ - 120$" },
      { item: "Reparation bois pourri (epoxy + finition)", price: "150$ - 400$" },
      { item: "Greffe de bois neuf (section pourrie)", price: "200$ - 500$" },
      { item: "Ponçage et refinition complete", price: "200$ - 600$" },
      { item: "Remplacement de seuil de porte", price: "150$ - 350$" },
    ],
    factors: [
      { title: "Etendue des dommages", desc: "Une porte qui colle est simple a reparer. Un cadre pourri sur toute la base necessite plus de travail." },
      { title: "Type de finition", desc: "Peinture, teinture ou vernis — chaque finition a un cout different et une duree de vie differente." },
      { title: "Accessibilite", desc: "Les fenetres en hauteur sont plus complexes a travailler." },
      { title: "Age et valeur patrimoniale", desc: "Les fenetres patrimoniales necessitent un travail plus minutieux pour preserver le cachet d'origine." },
    ],
    comparison: {
      title: "Reparation vs remplacement de porte en bois",
      rows: [
        { label: "Prix moyen", thermos: "150$ - 400$", complet: "1 500$ - 4 000$" },
        { label: "Preservation du cachet", thermos: "Oui", complet: "Non" },
        { label: "Delai", thermos: "1-3 jours", complet: "4-8 semaines" },
        { label: "Duree de vie apres reparation", thermos: "10-20 ans", complet: "25-30 ans" },
      ],
    },
    faq: [
      { q: "Est-ce possible de reparer une porte en bois plutot que la remplacer?", a: "Dans la grande majorite des cas, oui. Meme une porte avec du bois pourri peut etre reparee avec de l'epoxy ou une greffe de bois neuf, pour une fraction du cout de remplacement." },
      { q: "Combien coute la restauration d'une fenetre en bois patrimoniale?", a: "La restauration d'une fenetre patrimoniale coute entre 200$ et 600$ selon l'etat. C'est un investissement qui preserve la valeur et le cachet de votre propriete." },
    ],
    savings: "Economie moyenne de 1 500$ a 3 500$ vs le remplacement",
  },
  {
    slug: "desembuage",
    serviceSlug: "desembuage",
    title: "Desembuage de fenetres",
    metaTitle: "Prix desembuage fenetre 2026 | Alternative au remplacement | Vosthermos",
    metaDescription: "Combien coute le desembuage d'une fenetre au Quebec? Prix, avantages, duree de vie. Alternative economique au remplacement de thermos. 514-825-8411.",
    heroSubtitle: "Le desembuage coute entre 80$ et 175$ par fenetre. C'est une alternative encore plus economique au remplacement de thermos, mais avec certaines limites.",
    priceRange: { min: 80, max: 175, unit: "par fenetre" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Desembuage fenetre standard", price: "80$ - 125$" },
      { item: "Desembuage grande fenetre", price: "125$ - 175$" },
      { item: "Desembuage + traitement anti-buee", price: "+25$ par unite" },
      { item: "Forfait maison (5+ fenetres)", price: "Rabais de 10-15%" },
    ],
    factors: [
      { title: "Etat du thermos", desc: "Le desembuage fonctionne bien si la buee est recente. Si des depots blancs sont incrustes, le remplacement est preferable." },
      { title: "Taille de la fenetre", desc: "Les grandes fenetres coutent plus cher a traiter." },
      { title: "Nombre de fenetres", desc: "Un forfait pour plusieurs fenetres offre un meilleur prix unitaire." },
    ],
    comparison: {
      title: "Desembuage vs remplacement de thermos",
      rows: [
        { label: "Prix moyen", thermos: "100$ - 150$", complet: "200$ - 350$" },
        { label: "Duree de vie", thermos: "3-5 ans", complet: "15-25 ans" },
        { label: "Efficacite", thermos: "80-90%", complet: "100%" },
        { label: "Garantie", thermos: "2-3 ans", complet: "10 ans" },
      ],
    },
    faq: [
      { q: "Le desembuage est-il permanent?", a: "Le desembuage dure generalement 3 a 5 ans. C'est une solution intermediaire. Pour une solution permanente, le remplacement du thermos est recommande." },
      { q: "Quand choisir le desembuage vs le remplacement?", a: "Le desembuage est ideal quand la buee est legere et recente. Si le thermos a des depots blancs incrustes ou si la fenetre a plus de 20 ans, le remplacement est la meilleure option." },
    ],
    savings: "Economie de 50$ a 200$ par fenetre vs le remplacement de thermos",
  },
  {
    slug: "insertion-porte",
    serviceSlug: "insertion-porte",
    title: "Remplacement d'insertion de porte",
    metaTitle: "Prix remplacement insertion de porte 2026 | Vitrage porte entree | Vosthermos",
    metaDescription: "Combien coute le remplacement d'une insertion de porte d'entree? Prix vitrage, designs disponibles, installation. Grille 2026. 514-825-8411.",
    heroSubtitle: "Le remplacement d'une insertion de porte coute entre 200$ et 700$, comparativement a 2 000$ a 5 000$ pour une porte neuve. Le resultat est spectaculaire.",
    priceRange: { min: 200, max: 700, unit: "par insertion" },
    pricePerSqFt: null,
    tableRows: [
      { item: "Insertion verre clair standard", price: "200$ - 350$" },
      { item: "Insertion verre givre ou texture", price: "250$ - 400$" },
      { item: "Insertion decorative (fer forge, design)", price: "350$ - 600$" },
      { item: "Insertion pleine grandeur", price: "400$ - 700$" },
      { item: "Insertion demi-lune ou laterale", price: "200$ - 450$" },
    ],
    factors: [
      { title: "Type de verre", desc: "Verre clair, givre, texture, decoratif avec inserts de fer forge — chaque option a un prix different." },
      { title: "Dimension", desc: "Une insertion pleine grandeur coute plus cher qu'une demi-insertion." },
      { title: "Design", desc: "Les designs decoratifs avec inserts metalliques sont plus couteux mais transforment completement l'apparence de votre porte." },
    ],
    comparison: {
      title: "Remplacement insertion vs porte neuve",
      rows: [
        { label: "Prix moyen", thermos: "300$ - 500$", complet: "2 000$ - 5 000$" },
        { label: "Transformation visuelle", thermos: "Majeure", complet: "Complete" },
        { label: "Delai", thermos: "2-3 jours", complet: "4-8 semaines" },
        { label: "Installation", thermos: "Simple", complet: "Complexe" },
      ],
    },
    faq: [
      { q: "Peut-on changer le design de l'insertion sans changer la porte?", a: "Absolument! C'est meme l'un des avantages principaux. Vous pouvez passer d'un verre clair a un design decoratif pour transformer l'apparence de votre porte a une fraction du cout." },
      { q: "L'insertion est-elle aussi isolante qu'une porte neuve?", a: "Oui, nos insertions sont des unites scellees avec gaz argon et verre Low-E, offrant une isolation equivalente aux portes neuves." },
    ],
    savings: "Economie de 1 500$ a 4 000$ vs une porte neuve",
  },
];

export function getPricing(slug) {
  return PRICING.find((p) => p.slug === slug);
}
