export const PROBLEMS = [
  // === VITRES THERMOS / BUÉE ===
  { slug: "fenetre-embuee", title: "Fenetre embuee entre les vitres", shortTitle: "Fenetre embuee", category: "thermos", icon: "fas fa-cloud", serviceSlug: "remplacement-vitre-thermos", description: "La buee entre les deux vitres de votre fenetre thermos indique que le scellant est brise. L'humidite s'infiltre et reste prisonniere, causant un voile permanent qui ne part pas en frottant.", causes: ["Scellant perimetrique deteriore par les cycles gel-degel", "Age du thermos (duree de vie de 15 a 25 ans)", "Exposition directe au soleil accelerant le vieillissement", "Installation defectueuse a l'origine"], solutions: ["Remplacement du thermos (unite scellee) — solution permanente et service garanti", "Le desembuage peut etre tente si le scellant n'est pas completement deteriore", "Verification de tous les thermos de la maison, souvent plusieurs sont atteints en meme temps"], urgency: "modere", cost: "150$ a 350$ par thermos" },
  { slug: "condensation-entre-vitres", title: "Condensation entre les vitres de fenetre", shortTitle: "Condensation entre vitres", category: "thermos", icon: "fas fa-tint", serviceSlug: "remplacement-vitre-thermos", description: "La condensation qui apparait entre les deux panneaux de verre de votre fenetre est un signe clair que le scellant de l'unite thermos est defaillant. Le gaz argon s'echappe et l'humidite prend sa place.", causes: ["Bris du scellant hermetique de l'unite scellee", "Perte du gaz argon isolant entre les vitres", "Vieillissement naturel apres 15-25 ans", "Choc thermique ou vibrations repetees"], solutions: ["Remplacement de l'unite scellee (thermos) par une neuve avec gaz argon", "Ne pas attendre — la condensation peut causer de la moisissure sur le cadre", "Programme OPTI-FENETRE si plusieurs fenetres sont atteintes"], urgency: "modere", cost: "150$ a 350$ par unite" },
  { slug: "vitre-thermos-embuee", title: "Vitre thermos embuee — que faire?", shortTitle: "Thermos embue", category: "thermos", icon: "fas fa-eye-slash", serviceSlug: "remplacement-vitre-thermos", description: "Un thermos embue signifie que l'unite scellee a perdu son etancheite. L'air humide entre et la condensation apparait, surtout par temps froid. C'est irrecuperable sans intervention.", causes: ["Fin de vie utile du thermos (15-25 ans)", "Scellant deteriore par l'exposition aux elements", "Defaut de fabrication (rare mais possible)", "Pression causee par les variations de temperature"], solutions: ["Remplacement du thermos — la seule solution permanente", "Le desembuage peut prolonger la vie temporairement", "Verifier si d'autres fenetres montrent des signes similaires"], urgency: "modere", cost: "150$ a 350$" },
  { slug: "double-vitrage-brise", title: "Double vitrage brise ou fissure", shortTitle: "Double vitrage brise", category: "thermos", icon: "fas fa-exclamation-triangle", serviceSlug: "remplacement-vitre-thermos", description: "Un double vitrage fissure ou brise compromet immediatement l'isolation de votre maison et peut etre dangereux. L'air froid entre directement et votre facture de chauffage augmente.", causes: ["Impact d'un objet (balle, branche, grele)", "Choc thermique (changement brusque de temperature)", "Stress mecanique du cadre", "Vice de fabrication"], solutions: ["Remplacement urgent de l'unite scellee", "Couvrir temporairement avec un plastique en attendant la reparation", "Ne pas tenter de reparer soi-meme — risque de blessure"], urgency: "urgent", cost: "150$ a 400$ selon la taille" },
  { slug: "buee-fenetre-matin", title: "Buee sur les fenetres le matin", shortTitle: "Buee le matin", category: "thermos", icon: "fas fa-sun", serviceSlug: "remplacement-vitre-thermos", description: "Si la buee est a l'exterieur du verre, c'est normal et signe que votre fenetre isole bien. Si elle est ENTRE les vitres, votre thermos est defectueux. La difference est cruciale.", causes: ["Buee exterieure : phenomene naturel de condensation (pas un probleme)", "Buee interieure : taux d'humidite trop eleve dans la maison", "Buee entre les vitres : thermos defectueux, scellant brise"], solutions: ["Buee exterieure : rien a faire, c'est un signe que votre fenetre isole bien", "Buee interieure : ameliorer la ventilation, utiliser un deshumidificateur", "Buee entre les vitres : remplacement du thermos necessaire"], urgency: "faible", cost: "0$ a 350$ selon la cause" },
  { slug: "fenetre-givre-interieur", title: "Givre a l'interieur de la fenetre en hiver", shortTitle: "Givre interieur", category: "thermos", icon: "fas fa-snowflake", serviceSlug: "coupe-froid", description: "Du givre qui se forme a l'interieur de vos fenetres en hiver indique un serieux probleme d'isolation. L'air froid penetre et l'humidite interieure gele au contact de la vitre.", causes: ["Coupe-froid use ou manquant laissant passer l'air froid", "Calfeutrage exterieur deteriore", "Thermos en fin de vie avec perte d'isolation", "Fenetre simple vitrage non isolee"], solutions: ["Remplacement des coupe-froid — souvent suffisant pour regler le probleme", "Verification et refection du calfeutrage exterieur", "Si le thermos est embue, le remplacer aussi", "Programme OPTI-FENETRE pour traiter tous les problemes d'un coup"], urgency: "eleve", cost: "50$ a 350$ selon la cause" },
  { slug: "fenetre-froide-au-toucher", title: "Fenetre froide au toucher en hiver", shortTitle: "Fenetre froide", category: "thermos", icon: "fas fa-temperature-low", serviceSlug: "remplacement-vitre-thermos", description: "Une fenetre anormalement froide au toucher en hiver signifie qu'elle ne fait plus son travail d'isolation. Vous perdez de la chaleur et votre chauffage compense, augmentant votre facture.", causes: ["Thermos en fin de vie — le gaz argon s'est echappe", "Coupe-froid use laissant passer l'air", "Fenetre a simple vitrage (maisons anciennes)", "Cadre en aluminium sans coupure thermique"], solutions: ["Remplacement du thermos par un modele Low-E avec argon", "Ajout ou remplacement des coupe-froid", "Calfeutrage exterieur pour eliminer les infiltrations", "Evaluation gratuite pour identifier la cause exacte"], urgency: "modere", cost: "50$ a 400$" },

  // === COURANTS D'AIR / INFILTRATIONS ===
  { slug: "courant-air-fenetre", title: "Courant d'air qui passe par la fenetre", shortTitle: "Courant d'air fenetre", category: "infiltration", icon: "fas fa-wind", serviceSlug: "coupe-froid", description: "Un courant d'air perceptible pres de vos fenetres signifie que l'etancheite est compromise. Vous chauffez l'exterieur et votre confort en souffre. C'est un des problemes les plus courants au Quebec.", causes: ["Coupe-froid use, ecrase ou manquant", "Calfeutrage exterieur fissure ou decolle", "Fenetre mal ajustee dans son cadre", "Quincaillerie desajustee empechant la fermeture etanche"], solutions: ["Remplacement des coupe-froid — solution rapide et economique", "Refection du calfeutrage exterieur", "Ajustement de la quincaillerie de fermeture", "Verification complete dans le cadre du programme OPTI-FENETRE"], urgency: "eleve", cost: "30$ a 150$ par fenetre" },
  { slug: "fenetre-qui-siffle", title: "Fenetre qui siffle au vent", shortTitle: "Fenetre qui siffle", category: "infiltration", icon: "fas fa-volume-up", serviceSlug: "coupe-froid", description: "Un sifflement quand le vent souffle indique une infiltration d'air precise. C'est souvent un coupe-froid defectueux ou un point de calfeutrage deteriore qui cree cet effet de venturi.", causes: ["Coupe-froid comprime ou deplace laissant un passage d'air precis", "Fissure dans le calfeutrage exterieur", "Vis de fermeture desajustees (la fenetre ne presse pas assez sur le coupe-froid)", "Joint entre le cadre et le mur deteriore"], solutions: ["Remplacement du coupe-froid au point d'infiltration", "Refection du calfeutrage exterieur", "Ajustement des mecanismes de fermeture", "Test a la chandelle pour localiser l'infiltration exacte"], urgency: "modere", cost: "30$ a 150$" },
  { slug: "infiltration-eau-fenetre", title: "Infiltration d'eau par la fenetre", shortTitle: "Infiltration d'eau", category: "infiltration", icon: "fas fa-water", serviceSlug: "calfeutrage", description: "L'eau qui s'infiltre autour de votre fenetre peut causer des dommages importants : moisissure, pourriture du bois, deterioration des murs. C'est une urgence a traiter rapidement.", causes: ["Calfeutrage exterieur fissure, decolle ou manquant", "Solin mal installe au-dessus de la fenetre", "Drain de la fenetre coulissante bloque", "Cadre de fenetre en bois pourri laissant passer l'eau"], solutions: ["Refection complete du calfeutrage exterieur", "Verification et nettoyage des drains de fenetre", "Reparation du cadre en bois si necessaire", "Installation d'un solin si absent ou defectueux"], urgency: "urgent", cost: "100$ a 500$" },
  { slug: "moisissure-contour-fenetre", title: "Moisissure autour de la fenetre", shortTitle: "Moisissure fenetre", category: "infiltration", icon: "fas fa-biohazard", serviceSlug: "calfeutrage", description: "La moisissure noire ou verte autour de vos fenetres est causee par l'exces d'humidite. Elle peut etre un risque pour la sante et indique un probleme d'etancheite ou de ventilation.", causes: ["Infiltration d'eau par le calfeutrage deteriore", "Condensation excessive due a un thermos defectueux", "Manque de ventilation dans la piece", "Coupe-froid use laissant entrer l'air humide en ete et froid en hiver"], solutions: ["Nettoyer la moisissure avec un produit antifongique", "Refaire le calfeutrage exterieur et interieur", "Remplacer le thermos si la condensation est entre les vitres", "Ameliorer la ventilation de la piece"], urgency: "urgent", cost: "100$ a 400$" },
  { slug: "calfeutrage-fenetre-craque", title: "Calfeutrage de fenetre craque ou decolle", shortTitle: "Calfeutrage craque", category: "infiltration", icon: "fas fa-fill-drip", serviceSlug: "calfeutrage", description: "Le calfeutrage exterieur de vos fenetres est votre premiere barriere contre les elements. Quand il craque ou se decolle, l'eau et l'air froid s'infiltrent directement.", causes: ["Vieillissement naturel du scellant (5 a 10 ans)", "Exposition au soleil et aux UV", "Cycles de gel-degel repetitifs du climat quebecois", "Mauvaise preparation de surface lors de l'application precedente"], solutions: ["Retrait complet de l'ancien calfeutrage", "Application d'un scellant de qualite superieure adapte au climat quebecois", "Le calfeutrage devrait etre refait tous les 5 a 7 ans au Quebec"], urgency: "modere", cost: "15$ a 30$ par fenetre" },
  { slug: "scellant-fenetre-decolle", title: "Scellant de fenetre decolle", shortTitle: "Scellant decolle", category: "infiltration", icon: "fas fa-unlink", serviceSlug: "calfeutrage", description: "Un scellant decolle autour de vos fenetres laisse un espace par lequel l'eau de pluie et l'air froid peuvent s'infiltrer. C'est une reparation simple mais essentielle.", causes: ["Surface mal preparee lors de l'application", "Scellant de mauvaise qualite ou incompatible avec le materiau", "Mouvement du batiment (tassement, dilatation)", "Age du scellant depasse"], solutions: ["Retrait complet et reapplication avec un scellant de qualite", "Preparation minutieuse de la surface (nettoyage, appret si necessaire)", "Utilisation d'un scellant polyurethane ou silicone adapte au climat"], urgency: "modere", cost: "15$ a 30$ par fenetre" },

  // === COUPE-FROID ===
  { slug: "coupe-froid-use", title: "Coupe-froid use ou decolle", shortTitle: "Coupe-froid use", category: "coupe-froid", icon: "fas fa-minus-circle", serviceSlug: "coupe-froid", description: "Le coupe-froid est un joint souple qui assure l'etancheite quand votre fenetre est fermee. Avec le temps, il s'ecrase, se decolle ou se fendille, laissant passer l'air.", causes: ["Usure normale (duree de vie de 5 a 10 ans)", "Ecrasement permanent par la pression de fermeture", "Deterioration par les UV et la chaleur", "Nettoyage avec des produits chimiques agressifs"], solutions: ["Remplacement du coupe-froid par un modele adapte", "Nous avons des centaines de profils compatibles avec toutes les marques", "Installation rapide, generalement en moins d'une heure par fenetre"], urgency: "eleve", cost: "30$ a 80$ par fenetre" },

  // === FENÊTRES QUI COINCENT / MÉCANISMES ===
  { slug: "fenetre-difficile-ouvrir", title: "Fenetre difficile a ouvrir", shortTitle: "Fenetre difficile a ouvrir", category: "quincaillerie", icon: "fas fa-lock-open", serviceSlug: "remplacement-quincaillerie", description: "Une fenetre qui resiste quand vous essayez de l'ouvrir est frustrante et peut etre un risque de securite en cas d'urgence. Le probleme est souvent mecanique et reparable.", causes: ["Mecanisme d'ouverture use ou grippe", "Peinture qui colle le cadre", "Cadre en bois gonfle par l'humidite", "Quincaillerie desajustee ou cassee"], solutions: ["Lubrification et ajustement du mecanisme", "Remplacement de la quincaillerie defectueuse", "Rabotage du cadre si gonflement du bois", "Remplacement de la manivelle si c'est une fenetre a battant"], urgency: "modere", cost: "50$ a 200$" },
  { slug: "fenetre-bloquee", title: "Fenetre qui ne s'ouvre plus du tout", shortTitle: "Fenetre bloquee", category: "quincaillerie", icon: "fas fa-ban", serviceSlug: "remplacement-quincaillerie", description: "Une fenetre completement bloquee est un probleme de securite — vous ne pouvez plus aerer et en cas d'incendie, c'est une sortie en moins. Il faut agir rapidement.", causes: ["Mecanisme d'ouverture casse", "Peinture epaisse soudant le cadre", "Bois gonfle rendant l'ouverture impossible", "Verrou coince ou casse"], solutions: ["Remplacement du mecanisme d'ouverture", "Degagement du cadre et lubrification", "Remplacement de la quincaillerie defectueuse"], urgency: "urgent", cost: "75$ a 250$" },
  { slug: "fenetre-qui-ferme-mal", title: "Fenetre qui ne ferme pas completement", shortTitle: "Fenetre qui ferme mal", category: "quincaillerie", icon: "fas fa-times-circle", serviceSlug: "remplacement-quincaillerie", description: "Une fenetre qui ne ferme pas completement laisse entrer l'air froid, la pluie et les insectes. C'est souvent un probleme de quincaillerie facile a reparer.", causes: ["Crochet de fermeture desajuste ou casse", "Cadre deforme (affaissement du batiment)", "Mecanisme de verrouillage use", "Charniere pliee ou cassee"], solutions: ["Ajustement ou remplacement du mecanisme de fermeture", "Remplacement des charnieres si necessaire", "Verification de l'alignement du cadre"], urgency: "eleve", cost: "50$ a 200$" },
  { slug: "fenetre-difficile-verrouiller", title: "Fenetre difficile a verrouiller", shortTitle: "Fenetre difficile a verrouiller", category: "quincaillerie", icon: "fas fa-lock", serviceSlug: "remplacement-quincaillerie", description: "Si votre fenetre est difficile a verrouiller, le mecanisme de fermeture est probablement desajuste. C'est un probleme de securite et d'isolation.", causes: ["Came de verrouillage usee ou desajustee", "Gache mal alignee", "Cadre deforme empechant l'alignement", "Quincaillerie de mauvaise qualite"], solutions: ["Ajustement de la came et de la gache", "Remplacement du mecanisme de verrouillage", "Realignement du cadre si necessaire"], urgency: "modere", cost: "40$ a 150$" },
  { slug: "manivelle-fenetre-cassee", title: "Manivelle de fenetre cassee", shortTitle: "Manivelle cassee", category: "quincaillerie", icon: "fas fa-wrench", serviceSlug: "remplacement-quincaillerie", description: "La manivelle de votre fenetre a battant ou a auvent est le mecanisme que vous utilisez chaque jour. Quand elle casse, la fenetre devient inutilisable.", causes: ["Usure normale du mecanisme a engrenage", "Forcer sur une fenetre coincee", "Corrosion du mecanisme", "Piece de mauvaise qualite"], solutions: ["Remplacement de la manivelle par un modele compatible", "Nous avons des centaines de modeles en stock pour toutes les marques", "Installation en moins de 30 minutes"], urgency: "modere", cost: "30$ a 120$" },
  { slug: "loquet-fenetre-brise", title: "Loquet de fenetre brise ou use", shortTitle: "Loquet brise", category: "quincaillerie", icon: "fas fa-unlock", serviceSlug: "remplacement-quincaillerie", description: "Un loquet de fenetre brise compromet la securite de votre maison et l'etancheite de la fenetre. C'est une reparation simple et economique.", causes: ["Usure normale avec le temps", "Manipulation brusque", "Corrosion (surtout pres de la mer ou en milieu humide)", "Piece de qualite inferieure"], solutions: ["Remplacement du loquet par un modele identique ou compatible", "Ajustement du mecanisme de fermeture si necessaire", "Verification des autres loquets de la maison"], urgency: "modere", cost: "20$ a 80$" },
  { slug: "charniere-fenetre-cassee", title: "Charniere de fenetre cassee ou usee", shortTitle: "Charniere cassee", category: "quincaillerie", icon: "fas fa-tools", serviceSlug: "remplacement-quincaillerie", description: "Une charniere cassee fait que votre fenetre pend, se ferme mal ou ne s'ouvre plus correctement. C'est un probleme frequent sur les fenetres a battant et a auvent.", causes: ["Usure normale apres des annees d'utilisation", "Surcharge (fenetre trop lourde pour les charnieres)", "Corrosion par l'humidite", "Vent violent ayant force la fenetre"], solutions: ["Remplacement des charnieres par des modeles de qualite equivalente ou superieure", "Ajustement du cadre si la fenetre a ete endommagee", "Verification du poids de la fenetre par rapport aux charnieres"], urgency: "modere", cost: "50$ a 150$ par fenetre" },
  { slug: "fenetre-guillotine-bloquee", title: "Fenetre a guillotine bloquee", shortTitle: "Guillotine bloquee", category: "quincaillerie", icon: "fas fa-arrows-alt-v", serviceSlug: "remplacement-quincaillerie", description: "Les fenetres a guillotine sont courantes dans les triplex et duplex montrealais. Quand elles bloquent, c'est generalement un probleme de ressort ou de rail.", causes: ["Ressorts de balancement brises ou fatigues", "Rails encrasses ou deformes", "Peinture accumulee dans les rails", "Cadre en bois gonfle par l'humidite"], solutions: ["Remplacement des ressorts de balancement", "Nettoyage et lubrification des rails", "Degagement du cadre et ajustement"], urgency: "modere", cost: "75$ a 200$" },
  { slug: "quincaillerie-rouille", title: "Quincaillerie de porte ou fenetre rouillee", shortTitle: "Quincaillerie rouillee", category: "quincaillerie", icon: "fas fa-rust", serviceSlug: "remplacement-quincaillerie", description: "La rouille sur la quincaillerie de vos portes et fenetres indique une deterioration avancee. Les mecanismes rouilles grippent, se bloquent et finissent par casser.", causes: ["Exposition a l'humidite et aux intemperies", "Absence de traitement anticorrosion", "Condensation repetee sur les pieces metalliques", "Proximite de la mer ou environnement salin"], solutions: ["Remplacement complet de la quincaillerie rouillee", "Installation de pieces en acier inoxydable ou traitees anticorrosion", "Verification de l'ensemble de la quincaillerie de la maison"], urgency: "modere", cost: "30$ a 150$ par piece" },

  // === PORTES PATIO ===
  { slug: "porte-patio-coince", title: "Porte patio qui coince ou glisse mal", shortTitle: "Porte patio qui coince", category: "porte-patio", icon: "fas fa-door-open", serviceSlug: "remplacement-quincaillerie", description: "Une porte patio qui coince ou glisse difficilement est un des problemes les plus courants. C'est souvent un probleme de roulettes usees ou de rail sale.", causes: ["Roulettes usees, aplaties ou cassees", "Rail encombre de debris ou deforme", "Porte desalignee dans son cadre", "Salete accumulee dans le mecanisme"], solutions: ["Remplacement des roulettes — regle le probleme dans 80% des cas", "Nettoyage et ajustement du rail", "Realignement de la porte dans son cadre", "Lubrification des mecanismes"], urgency: "modere", cost: "75$ a 200$" },
  { slug: "roulette-porte-patio-usee", title: "Roulette de porte patio usee ou cassee", shortTitle: "Roulette porte patio", category: "porte-patio", icon: "fas fa-circle-notch", serviceSlug: "remplacement-quincaillerie", description: "Les roulettes sont les pieces qui permettent a votre porte patio de glisser sur le rail. Avec le temps, elles s'usent, s'aplatissent et la porte devient difficile a manipuler.", causes: ["Usure normale (duree de vie de 10 a 15 ans)", "Accumulation de salete dans le mecanisme", "Surcharge (porte tres lourde)", "Roulettes de mauvaise qualite d'origine"], solutions: ["Remplacement des roulettes par des modeles de qualite superieure", "Nettoyage et inspection du rail", "Ajustement de la hauteur de la porte apres remplacement", "Nous avons des roulettes compatibles avec toutes les marques"], urgency: "modere", cost: "75$ a 175$" },
  { slug: "porte-patio-rail-use", title: "Rail de porte patio use ou deforme", shortTitle: "Rail porte patio", category: "porte-patio", icon: "fas fa-grip-lines", serviceSlug: "remplacement-quincaillerie", description: "Le rail de votre porte patio guide le mouvement de la porte. Un rail use, deforme ou encombre empeche la porte de glisser correctement.", causes: ["Usure par le frottement continu", "Deformation due au poids de la porte", "Accumulation de debris, sable et salete", "Dommages lors de demenagements ou renovations"], solutions: ["Nettoyage en profondeur et ajustement du rail", "Remplacement du rail si trop endommage", "Installation d'un couvre-rail si le seuil est abime", "Ajustement des roulettes apres l'intervention"], urgency: "modere", cost: "100$ a 300$" },
  { slug: "serrure-porte-patio-bloquee", title: "Serrure de porte patio bloquee ou brisee", shortTitle: "Serrure porte patio", category: "porte-patio", icon: "fas fa-key", serviceSlug: "remplacement-quincaillerie", description: "Une serrure de porte patio defectueuse est un probleme de securite important. Vous ne pouvez plus verrouiller votre maison correctement.", causes: ["Mecanisme de verrouillage use ou grippe", "Cle cassee dans la serrure", "Cylindre de serrure endommage", "Desalignement de la porte empechant le verrouillage"], solutions: ["Remplacement de la serrure ou du cylindre", "Realignement de la porte si necessaire", "Installation d'une serrure de securite amelioree", "Verification du mecanisme de crochet"], urgency: "urgent", cost: "75$ a 250$" },
  { slug: "poignee-porte-patio-cassee", title: "Poignee de porte patio cassee", shortTitle: "Poignee porte patio", category: "porte-patio", icon: "fas fa-hand-paper", serviceSlug: "remplacement-quincaillerie", description: "La poignee est la piece la plus sollicitee de votre porte patio. Quand elle casse, l'ouverture et la fermeture deviennent impossibles ou tres difficiles.", causes: ["Usure mecanique apres des milliers d'utilisations", "Plastique fragile sur les modeles economiques", "Manipulation brusque ou forcee", "Gel affectant les mecanismes en hiver"], solutions: ["Remplacement de la poignee par un modele compatible", "Plus de 200 modeles en stock pour toutes les marques", "Installation rapide en moins de 30 minutes"], urgency: "modere", cost: "30$ a 120$" },
  { slug: "porte-patio-laisse-passer-air", title: "Porte patio qui laisse passer l'air froid", shortTitle: "Air froid porte patio", category: "porte-patio", icon: "fas fa-wind", serviceSlug: "coupe-froid", description: "Sentir de l'air froid pres de votre porte patio en hiver est un signe que les joints ne font plus leur travail. Vous perdez de la chaleur et votre confort diminue.", causes: ["Coupe-froid use ou ecrase", "Porte desalignee ne pressant plus sur les joints", "Calfeutrage exterieur deteriore", "Seuil de porte endommage"], solutions: ["Remplacement des coupe-froid de la porte", "Ajustement des roulettes pour realigner la porte", "Refection du calfeutrage exterieur", "Remplacement du seuil si necessaire"], urgency: "eleve", cost: "50$ a 200$" },

  // === PORTES EN BOIS ===
  { slug: "porte-bois-qui-colle", title: "Porte en bois qui colle ou frotte", shortTitle: "Porte bois qui colle", category: "porte-bois", icon: "fas fa-door-closed", serviceSlug: "reparation-portes-bois", description: "Une porte en bois qui colle ou frotte est un probleme frequent au Quebec, cause par les variations d'humidite entre l'ete et l'hiver.", causes: ["Gonflement du bois par l'humidite (surtout au printemps et en ete)", "Affaissement des charnieres", "Tassement de la maison deformant le cadre", "Accumulation de couches de peinture"], solutions: ["Rabotage de la porte aux points de frottement", "Ajustement ou remplacement des charnieres", "Ponçage et refinition si accumulation de peinture", "Traitement du bois pour prevenir le gonflement"], urgency: "faible", cost: "75$ a 250$" },
  { slug: "porte-entree-gonflee", title: "Porte d'entree en bois gonflee", shortTitle: "Porte entree gonflee", category: "porte-bois", icon: "fas fa-expand-arrows-alt", serviceSlug: "reparation-portes-bois", description: "Le bois est un materiau vivant qui reagit a l'humidite. Au Quebec, les variations extremes de temperature et d'humidite font gonfler les portes d'entree en bois.", causes: ["Humidite elevee au printemps et en ete", "Vernis ou peinture deteriore laissant l'humidite penetrer le bois", "Mauvaise ventilation entre la porte et la contre-porte", "Exposition directe a la pluie"], solutions: ["Rabotage pour retrouver un jeu adequat", "Application d'un scellant ou vernis protecteur sur toutes les surfaces", "Ajustement des charnieres et du seuil", "Installation d'un solin ou d'un auvent si exposition directe a la pluie"], urgency: "modere", cost: "100$ a 350$" },
  { slug: "cadre-fenetre-pourri", title: "Cadre de fenetre en bois pourri", shortTitle: "Cadre pourri", category: "porte-bois", icon: "fas fa-bug", serviceSlug: "reparation-portes-bois", description: "Un cadre de fenetre pourri compromet l'etancheite, l'isolation et la securite de votre fenetre. Au Quebec, c'est un probleme frequent sur les maisons de plus de 30 ans.", causes: ["Infiltration d'eau prolongee par un calfeutrage deteriore", "Manque d'entretien du bois (peinture, vernis)", "Contact direct du bois avec la maconnerie sans protection", "Condensation repetee sur le cadre interieur"], solutions: ["Reparation avec du bois epoxy si la pourriture est localisee", "Remplacement partiel du cadre si la structure est atteinte", "Refection complete du calfeutrage apres reparation", "Application d'un traitement preservatif sur le bois neuf"], urgency: "urgent", cost: "200$ a 600$" },
  { slug: "porte-bois-pourri-bas", title: "Bas de porte en bois pourri", shortTitle: "Bas porte pourri", category: "porte-bois", icon: "fas fa-level-down-alt", serviceSlug: "reparation-portes-bois", description: "Le bas des portes en bois est la zone la plus vulnerable a la pourriture. L'eau de pluie, la neige fondante et les eclaboussures attaquent le bois constantement.", causes: ["Exposition repetee a l'eau et a la neige", "Seuil de porte mal draine", "Peinture ou vernis deteriore au bas de la porte", "Absence de coupe-eau ou de solin"], solutions: ["Reparation avec du bois epoxy pour les cas mineurs", "Greffe de bois neuf si la pourriture est etendue", "Application d'un traitement impermeabilisant", "Installation d'un coupe-eau en aluminium pour proteger le bas"], urgency: "eleve", cost: "150$ a 450$" },
  { slug: "peinture-fenetre-ecaille", title: "Peinture de fenetre en bois qui s'ecaille", shortTitle: "Peinture qui s'ecaille", category: "porte-bois", icon: "fas fa-paint-roller", serviceSlug: "reparation-portes-bois", description: "La peinture qui s'ecaille sur vos fenetres en bois n'est pas qu'un probleme esthetique — c'est le debut de la deterioration du bois sous-jacent.", causes: ["Age de la peinture (duree de vie de 5 a 10 ans en exterieur)", "Preparation inadequate de la surface lors de la derniere peinture", "Humidite emprisonnee sous la peinture", "Exposition intense au soleil et aux UV"], solutions: ["Grattage et ponçage de la peinture ecaillee", "Traitement du bois si deterioration visible", "Application d'un appret et de deux couches de peinture exterieure de qualite", "Entretien regulier tous les 5 a 7 ans"], urgency: "modere", cost: "100$ a 300$ par fenetre" },
  { slug: "porte-qui-grince", title: "Porte qui grince", shortTitle: "Porte qui grince", category: "porte-bois", icon: "fas fa-volume-down", serviceSlug: "remplacement-quincaillerie", description: "Un grincement de porte est generalement cause par des charnieres seches ou usees. C'est simple a reparer mais peut indiquer un probleme d'alignement.", causes: ["Charnieres seches manquant de lubrification", "Charnieres usees avec jeu excessif", "Porte desalignee mettant pression sur les charnieres", "Vis de charnieres desserrees"], solutions: ["Lubrification des charnieres avec un lubrifiant au silicone", "Remplacement des charnieres si usees", "Resserrage des vis et ajustement de l'alignement"], urgency: "faible", cost: "20$ a 100$" },

  // === MOUSTIQUAIRES ===
  { slug: "moustiquaire-dechiree", title: "Moustiquaire dechiree ou trouee", shortTitle: "Moustiquaire dechiree", category: "moustiquaire", icon: "fas fa-border-all", serviceSlug: "moustiquaires-sur-mesure", description: "Une moustiquaire dechiree laisse entrer les insectes et rend inutile votre fenetre moustiquaire. C'est une reparation simple et economique.", causes: ["Griffures d'animaux domestiques", "Manipulation brusque lors de l'installation/retrait", "Vieillissement et fragilisation du materiau", "Impact d'un objet"], solutions: ["Remplacement de la toile de moustiquaire dans le cadre existant", "Fabrication d'une moustiquaire neuve sur mesure si le cadre est aussi endommage", "Choix de toile en fibre de verre (standard) ou en aluminium (plus resistant)"], urgency: "faible", cost: "25$ a 100$ par moustiquaire" },
  { slug: "moustiquaire-qui-tombe", title: "Moustiquaire qui ne tient pas en place", shortTitle: "Moustiquaire qui tombe", category: "moustiquaire", icon: "fas fa-arrow-down", serviceSlug: "moustiquaires-sur-mesure", description: "Une moustiquaire qui tombe ou ne reste pas en place est un probleme de systeme de fixation. Les clips, ressorts ou rails sont uses.", causes: ["Clips de retention casses ou uses", "Ressorts de tension fatigues", "Cadre de moustiquaire deforme", "Mauvais format (moustiquaire trop petite pour l'ouverture)"], solutions: ["Remplacement des clips ou des ressorts de fixation", "Ajustement du cadre de la moustiquaire", "Fabrication d'une moustiquaire sur mesure aux bonnes dimensions"], urgency: "faible", cost: "15$ a 75$" },
  { slug: "moustiquaire-cadre-tordu", title: "Cadre de moustiquaire tordu ou plie", shortTitle: "Cadre moustiquaire tordu", category: "moustiquaire", icon: "fas fa-compress-alt", serviceSlug: "moustiquaires-sur-mesure", description: "Un cadre de moustiquaire tordu empeche une installation correcte et laisse des espaces par lesquels les insectes entrent.", causes: ["Manipulation brusque", "Entreposage inadequat en hiver", "Vent violent", "Cadre en aluminium mince fragile"], solutions: ["Redressage du cadre si la deformation est legere", "Fabrication d'un nouveau cadre sur mesure si trop endommage", "Choix d'un cadre plus robuste pour les emplacements exposes"], urgency: "faible", cost: "30$ a 100$" },

  // === INSERTIONS DE PORTE ===
  { slug: "insertion-porte-embuee", title: "Insertion de porte embuee", shortTitle: "Insertion embuee", category: "insertion", icon: "fas fa-th-large", serviceSlug: "insertion-porte", description: "L'insertion vitree de votre porte d'entree est embuee entre les vitres? C'est le meme probleme qu'un thermos de fenetre — le scellant est brise.", causes: ["Scellant de l'unite scellee deteriore", "Age de l'insertion (meme duree de vie qu'un thermos)", "Exposition aux elements plus intense sur une porte", "Vibrations repetees de la porte qui ouvre et ferme"], solutions: ["Remplacement de l'insertion par une neuve", "Choix parmi plusieurs designs (clair, givre, decoratif)", "Conservation du cadre de porte existant", "Installation rapide en quelques heures"], urgency: "modere", cost: "200$ a 600$" },
  { slug: "vitrage-porte-brise", title: "Vitrage de porte d'entree brise", shortTitle: "Vitrage porte brise", category: "insertion", icon: "fas fa-exclamation-circle", serviceSlug: "insertion-porte", description: "Un vitrage de porte brise est une urgence — c'est un risque de securite et d'infiltration. Nous pouvons remplacer l'insertion sans changer la porte complete.", causes: ["Impact d'un objet", "Tentative d'effraction", "Choc thermique", "Defaut du verre"], solutions: ["Remplacement rapide de l'insertion vitree", "Securisation temporaire en attendant l'intervention", "Choix de verre trempe pour une meilleure resistance", "Pas besoin de remplacer la porte complete"], urgency: "urgent", cost: "250$ a 700$" },

  // === DESEMBUAGE ===
  { slug: "vitre-opaque-blanchatre", title: "Vitre qui devient opaque ou blanchatre", shortTitle: "Vitre opaque", category: "desembuage", icon: "fas fa-low-vision", serviceSlug: "desembuage", description: "Une vitre qui devient progressivement opaque ou blanchatre a l'interieur du thermos est un signe avance de deterioration. Les depots mineraux s'accumulent sur le verre.", causes: ["Infiltration d'humidite prolongee dans le thermos", "Depots de mineraux sur la surface interieure du verre", "Stade avance d'un thermos defectueux", "Exposition a des conditions extremes"], solutions: ["Desembuage professionnel si les depots sont legers", "Remplacement du thermos si les depots sont incrustes", "Le desembuage est moins couteux mais ne regle pas la cause", "Le remplacement est la solution permanente avec garantie"], urgency: "modere", cost: "100$ a 350$" },

  // === FENÊTRES BRUYANTES ===
  { slug: "fenetre-bruyante", title: "Fenetre qui laisse passer le bruit", shortTitle: "Fenetre bruyante", category: "isolation", icon: "fas fa-deaf", serviceSlug: "remplacement-vitre-thermos", description: "Si le bruit exterieur penetre facilement par vos fenetres, c'est un signe que l'isolation acoustique est insuffisante. Un thermos performant reduit considerablement le bruit.", causes: ["Thermos simple sans gaz argon", "Coupe-froid use laissant passer le son", "Simple vitrage sur les maisons anciennes", "Cadre mal isole"], solutions: ["Remplacement du thermos par un modele avec gaz argon et verre Low-E", "Remplacement des coupe-froid pour une meilleure etancheite", "Option de vitrage acoustique pour les zones tres bruyantes"], urgency: "faible", cost: "200$ a 500$ par fenetre" },

  // === SÉCURITÉ ===
  { slug: "fenetre-ne-verrouille-plus", title: "Fenetre qui ne verrouille plus", shortTitle: "Fenetre non securisee", category: "securite", icon: "fas fa-shield-alt", serviceSlug: "remplacement-quincaillerie", description: "Une fenetre qui ne verrouille pas est une invitation pour les cambrioleurs et un risque pour la securite de votre famille. C'est souvent un simple probleme de quincaillerie.", causes: ["Mecanisme de verrouillage casse ou use", "Fenetre desalignee empechant le verrouillage", "Came ou gache deformee", "Poignee de verrouillage brisee"], solutions: ["Remplacement du mecanisme de verrouillage", "Realignement de la fenetre", "Installation d'un systeme de verrouillage ameliore"], urgency: "urgent", cost: "40$ a 150$" },

  // === ÉNERGIE / FACTURES ===
  { slug: "facture-chauffage-elevee", title: "Facture de chauffage trop elevee a cause des fenetres", shortTitle: "Facture chauffage elevee", category: "energie", icon: "fas fa-file-invoice-dollar", serviceSlug: "remplacement-vitre-thermos", description: "Vos fenetres et portes representent jusqu'a 25% des pertes de chaleur de votre maison. Des fenetres deficientes peuvent augmenter votre facture de chauffage de plusieurs centaines de dollars par annee.", causes: ["Thermos en fin de vie sans pouvoir isolant", "Coupe-froid uses laissant passer l'air", "Calfeutrage deteriore", "Fenetres simple vitrage non isolees"], solutions: ["Programme OPTI-FENETRE : remise a neuf complete pour une fraction du cout de remplacement", "Remplacement des thermos par des modeles Low-E avec argon", "Remplacement de tous les coupe-froid", "Refection du calfeutrage exterieur"], urgency: "modere", cost: "Programme OPTI-FENETRE a partir de 3 000$" },
  { slug: "fenetre-qui-forme-glace", title: "Glace qui se forme sur les fenetres", shortTitle: "Glace sur fenetres", category: "energie", icon: "fas fa-icicles", serviceSlug: "coupe-froid", description: "De la glace qui se forme sur l'interieur de vos fenetres en hiver est un signe serieux de probleme d'isolation. L'air froid penetre et l'humidite interieure gele.", causes: ["Coupe-froid completement use", "Calfeutrage exterieur absent ou deteriore", "Thermos sans pouvoir isolant (gaz argon disparu)", "Humidite interieure trop elevee combinee a un froid extreme"], solutions: ["Remplacement urgent des coupe-froid", "Verification et refection du calfeutrage", "Remplacement du thermos si necessaire", "Programme OPTI-FENETRE pour tout traiter en une seule intervention"], urgency: "urgent", cost: "50$ a 400$" },

  // === ESTHÉTIQUE ===
  { slug: "fenetre-jaunie", title: "Cadre de fenetre PVC jauni", shortTitle: "Fenetre jaunie", category: "esthetique", icon: "fas fa-palette", serviceSlug: "remplacement-quincaillerie", description: "Les cadres de fenetres en PVC blanc jaunissent avec le temps a cause de l'exposition aux UV. C'est principalement esthetique mais peut indiquer un vieillissement general.", causes: ["Exposition prolongee aux rayons UV du soleil", "Vieillissement naturel du PVC", "Nettoyage avec des produits abrasifs", "Qualite du PVC d'origine"], solutions: ["Nettoyage avec un produit specialise pour PVC", "Ponçage leger et application d'un renovateur de PVC", "Dans les cas avances, seul le remplacement du cadre est efficace"], urgency: "faible", cost: "20$ a 50$ en produits, ou remplacement" },
  { slug: "fenetre-coulissante-bloquee", title: "Fenetre coulissante qui ne glisse plus", shortTitle: "Coulissante bloquee", category: "quincaillerie", icon: "fas fa-arrows-alt-h", serviceSlug: "remplacement-quincaillerie", description: "Une fenetre coulissante qui ne glisse plus est souvent causee par des rails encrasses ou des roulettes usees, similaire au probleme de porte-patio.", causes: ["Rails encrasses par la poussiere et les debris", "Roulettes de coulissement usees ou aplaties", "Cadre deforme par le tassement du batiment", "Accumulation de peinture dans les rails"], solutions: ["Nettoyage en profondeur des rails", "Remplacement des roulettes de coulissement", "Lubrification avec un lubrifiant au silicone", "Ajustement du cadre si necessaire"], urgency: "modere", cost: "50$ a 175$" },
  { slug: "porte-moustiquaire-dechiree", title: "Porte moustiquaire dechiree ou abimee", shortTitle: "Porte moustiquaire abimee", category: "moustiquaire", icon: "fas fa-door-open", serviceSlug: "moustiquaires-sur-mesure", description: "La toile de votre porte moustiquaire est dechiree, deformee ou percee? C'est un probleme tres frequent, surtout avec des animaux ou des enfants.", causes: ["Animaux domestiques qui poussent sur la toile", "Enfants qui appuient contre la moustiquaire", "Vent violent qui deforme le cadre", "Vieillissement et fragilisation du materiau"], solutions: ["Remplacement de la toile dans le cadre existant", "Fabrication d'une porte moustiquaire neuve sur mesure", "Option de toile resistant aux animaux (pet screen)", "Ajustement du ferme-porte pour eviter les claquements"], urgency: "faible", cost: "40$ a 200$" },
  { slug: "porte-entree-difficile-fermer", title: "Porte d'entree difficile a fermer en hiver", shortTitle: "Porte difficile en hiver", category: "porte-bois", icon: "fas fa-snowflake", serviceSlug: "reparation-portes-bois", description: "En hiver au Quebec, les portes d'entree en bois peuvent devenir difficiles a fermer a cause du gel et des changements d'humidite. Le bois travaille et la porte ne s'aligne plus avec le cadre.", causes: ["Gel faisant gonfler le seuil et le cadre", "Accumulation de glace sous le seuil", "Coupe-froid trop epais apres remplacement", "Charnieres desajustees par le poids de la porte"], solutions: ["Ajustement des charnieres et de la plaque de gache", "Rabotage leger si le bois a gonfle", "Nettoyage de la glace accumulee sous le seuil", "Remplacement du coupe-froid par un modele adapte a l'hiver"], urgency: "eleve", cost: "75$ a 250$" },
  { slug: "fenetre-sous-sol-infiltration", title: "Infiltration d'eau par les fenetres du sous-sol", shortTitle: "Infiltration sous-sol", category: "infiltration", icon: "fas fa-water", serviceSlug: "calfeutrage", description: "Les fenetres de sous-sol sont particulierement vulnerables aux infiltrations d'eau, surtout au printemps lors de la fonte des neiges. L'eau s'accumule dans la margelle et penetre par le calfeutrage deteriore.", causes: ["Calfeutrage exterieur fissure ou absent autour de la fenetre", "Margelle (puits de fenetre) mal drainee", "Pente du terrain dirigeant l'eau vers la fondation", "Joint entre la fenetre et la fondation deteriore"], solutions: ["Refection complete du calfeutrage exterieur", "Nettoyage et verification du drain de la margelle", "Installation d'un couvercle de margelle si absent", "Verification de la pente du terrain autour de la fondation"], urgency: "urgent", cost: "100$ a 400$" },
];

export function getProblem(slug) {
  return PROBLEMS.find((p) => p.slug === slug);
}

export function getProblemsByCategory(category) {
  return PROBLEMS.filter((p) => p.category === category);
}

export const PROBLEM_CATEGORIES = [
  { slug: "thermos", label: "Vitres thermos et buee", icon: "fas fa-cloud" },
  { slug: "infiltration", label: "Courants d'air et infiltrations", icon: "fas fa-wind" },
  { slug: "coupe-froid", label: "Coupe-froid", icon: "fas fa-minus-circle" },
  { slug: "quincaillerie", label: "Mecanismes et quincaillerie", icon: "fas fa-cogs" },
  { slug: "porte-patio", label: "Portes patio", icon: "fas fa-door-open" },
  { slug: "porte-bois", label: "Portes et fenetres en bois", icon: "fas fa-tree" },
  { slug: "moustiquaire", label: "Moustiquaires", icon: "fas fa-border-all" },
  { slug: "insertion", label: "Insertions de porte", icon: "fas fa-th-large" },
  { slug: "desembuage", label: "Desembuage", icon: "fas fa-eye-slash" },
  { slug: "isolation", label: "Isolation acoustique", icon: "fas fa-deaf" },
  { slug: "securite", label: "Securite", icon: "fas fa-shield-alt" },
  { slug: "energie", label: "Efficacite energetique", icon: "fas fa-bolt" },
  { slug: "esthetique", label: "Esthetique", icon: "fas fa-palette" },
];
