[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Configuration pour les vidéos MP4
[[headers]]
  for = "/videos/*"
  [headers.values]
    "Content-Type" = "video/mp4"
    "Cache-Control" = "public, max-age=31536000"
    "Access-Control-Allow-Origin" = "*"

# Configuration Netlify Identity
[template.environment]
  NETLIFY_IDENTITY_ENABLE = "true"

# Configuration Netlify CMS
[backend]
  name = "git-gateway"
  branch = "main"
