const fr = {
  locale: "fr",
  documentTitle: "Mesures de fenêtres | Vosthermos",
  brandAlt: "Vosthermos",
  common: {
    close: "Fermer",
    cancel: "Annuler",
    continue: "Continuer",
    back: "Retour",
    confirm: "Confirmer",
    retry: "Réessayer",
    yes: "Oui",
    no: "Non",
    unknown: "Je ne sais pas / Inconnu",
    choose: "Choisir",
    optional: "Facultatif",
  },
  modes: {
    client: "Mesures client",
    technician: "Mesures finales",
    admin: "Fiche de mesures",
    phone: "Mesures téléphone",
    approximate: "Pré-soumission",
  },
  loading: {
    dossier: "Ouverture de votre dossier…",
    unavailableTitle: "Lien non disponible",
    unavailableBody: "Communiquez avec Vosthermos pour recevoir un nouveau lien.",
    alreadyReceivedTitle: "Mesures reçues",
    alreadyReceivedBody: "Notre équipe peut maintenant préparer votre soumission.",
  },
  progress: {
    title: "Étapes de mesure",
    measured: "mesurés",
    summary: "{{complete}} / {{total}} mesurés",
    windowSummary: "{{complete}} thermos sur {{total}} mesurés dans {{window}}",
    dossierSummary: "{{complete}} thermos sur {{total}} mesurés dans le dossier",
    paneComplete: "Mesuré",
    paneInProgress: "Mesures en cours",
    paneEmpty: "À mesurer",
    paneMissing: "Mesures à remplir",
    allComplete: "Toutes les mesures sont remplies",
  },
  windows: {
    title: "Fenêtres",
    defaultName: "Fenêtre {{number}}",
    firstDefaultName: "Salon",
    count: "{{count}} fenêtre(s)",
    thermosCount: "{{count}} thermos",
    add: "Ajouter une autre fenêtre",
    addHelp: "Créer un nouveau plan de vitrage",
    rename: "Renommer la fenêtre",
    renameAria: "Renommer {{code}} · {{name}}",
    nameField: "Nom de la pièce ou de la fenêtre",
    namePlaceholder: "Ex. Salon",
    nameRequired: "Entrez un nom pour cette fenêtre.",
    added: "{{code}} ajoutée.",
    renamed: "{{code}} renommée « {{name}} ».",
    selectedAria: "Ouvrir {{code}} · {{name}}",
  },
  models: {
    toolbarAria: "Choisir un type de fenêtre ou prendre une photo",
    chooseType: "Choisir un type de fenêtre",
    selection: "Sélection :",
    quickConfigurations: "Configurations rapides",
    menuAria: "Types de fenêtres",
    custom: "Disposition personnalisée",
    customSummary: "Disposition personnalisée · {{count}} thermos",
    gridSummary: "{{columns}} colonne(s) × {{rows}} rangée(s) · {{count}} thermos",
    currentAlreadyApplied: "La disposition « {{label}} » est déjà appliquée.",
    changeConfirmation: "Changer la disposition effacera les mesures de {{code}}. Continuer?",
    created: "Disposition « {{label}} » créée. {{count}} thermos à mesurer.",
    detected: "Disposition détectée : {{label}}.",
  },
  photo: {
    take: "Prendre une photo",
    retake: "Reprendre la photo",
    inputAria: "Prendre une photo de la fenêtre",
    detectedAutomatically: "Les divisions seront détectées automatiquement",
    analyzing: "Analyse de la photo…",
    analyzingHelp: "Le dessin se crée automatiquement",
    analyzingMessage: "Analyse automatique de la photo…",
    replaceHelp: "Une nouvelle photo remplacera cette analyse",
    invalid: "Choisissez une photo de fenêtre valide.",
    uploading: "Téléversement de la photo…",
    uploaded: "Photo ajoutée au dossier.",
    applied: "Photo analysée · disposition « {{label}} » appliquée.",
    retained: "Photo conservée · dessin non modifié.",
    failed: "Photo conservée. Les divisions n’ont pas été reconnues : reprenez-la bien de face ou choisissez un type.",
    uploadFailed: "La photo n’a pas pu être téléversée.",
    analysisFailed: "La photo est conservée, mais l’analyse automatique a échoué.",
    analysisLimit: "La limite d’analyses automatiques est atteinte. Corrigez le dessin manuellement.",
    linked: "Photo liée à cette fenêtre.",
    adminPreview: "Photo de référence",
    adminPreviewAlt: "Photo de {{code}} · {{name}}",
  },
  canvas: {
    aria: "Dessin interactif de la fenêtre",
    tapToSelect: "Toucher pour choisir",
    editing: "Vous éditez",
    selectedLabel: "{{code}}, thermos {{pane}}. Vous éditez ce thermos.",
    availableLabel: "{{code}}, thermos {{pane}}. Sélectionner ce thermos.",
    editSelected: "Modifier le thermos sélectionné",
    editSelectedHelp: "Diviser verticalement ou horizontalement",
    noSelection: "Aucun thermos sélectionné",
    selectedThermos: "Thermos sélectionné",
    dividerAria: "Séparation {{axis}} {{index}}",
    dividerLinked: ", continue sur toutes les rangées",
    dividerVerticalTitle: "Glisser à gauche ou à droite",
    dividerHorizontalTitle: "Glisser vers le haut ou le bas",
    equalize: "Répartir également",
    equalized: "Toutes les divisions de {{code}} ont été réparties également.",
    reset: "Réinitialiser le dessin",
    resetConfirmation: "Réinitialiser seulement {{code}} et ses mesures?",
    resetDone: "{{code}} a été réinitialisée.",
    maximumReached: "Maximum de {{max}} thermos atteint dans {{code}}.",
  },
  measurements: {
    title: "Mesures",
    unit: "Unité",
    unitChanged: "Unité de mesure : {{unit}}.",
    units: { in: "po", mm: "mm", cm: "cm" },
    width: "Largeur",
    height: "Hauteur",
    thickness: "Épaisseur",
    fraction: "Fraction {{dimension}}",
    widthPlaceholder: "Ex. 32",
    heightPlaceholder: "Ex. 48",
    thicknessPlaceholder: "Ex. 1",
    required: "Requis",
    clientThicknessOptional: "Facultative pour une pré-soumission; requise avant la commande.",
    invalid: "Entrez une mesure valide.",
    maximum: "Maximum {{value}} {{unit}}.",
    widthHeightRequired: "La largeur et la hauteur sont requises.",
    finalDimensionsRequired: "La largeur, la hauteur et l’épaisseur sont requises pour une mesure finale.",
  },
  options: {
    title: "Options du thermos",
    lowE: "Low-E",
    argon: "Argon",
    tempered: "Trempé",
    laminated: "Laminé",
    spacer: "Intercalaire",
    glazing: "Vitrage",
    access: "Accès",
    notes: "Notes particulières",
    notesPlaceholder: "Forme, défaut, accès, particularité…",
    spacerChoices: {
      empty: "Choisir",
      unknown: "Je ne sais pas / Inconnu",
      black: "Noir",
      gray: "Gris",
      white: "Blanc",
      stainless: "Inox",
    },
    glazingChoices: {
      empty: "Choisir",
      unknown: "Je ne sais pas / Inconnu",
      double: "Double",
      triple: "Triple",
      single: "Simple",
    },
    accessChoices: {
      empty: "Choisir",
      withLadder: "Avec échelle",
      withoutLadder: "Sans échelle",
    },
    decorative: {
      title: "Carreaux décoratifs",
      help: "Ajouter des lignes sans créer de nouveaux thermos",
      instruction: "Choisissez le nombre de lignes dans ce thermos seulement.",
      vertical: "Vertical",
      horizontal: "Horizontal",
      addVertical: "Ajouter une ligne verticale",
      removeVertical: "Retirer une ligne verticale",
      addHorizontal: "Ajouter une ligne horizontale",
      removeHorizontal: "Retirer une ligne horizontale",
    },
  },
  modals: {
    rename: {
      title: "Renommer la fenêtre",
      save: "Enregistrer",
    },
    split: {
      title: "Diviser ce thermos",
      intro: "Créez de 2 à 4 thermos dans la section sélectionnée.",
      optionsAria: "Options de division",
      direction: "Choisissez le sens",
      vertical: "Vertical",
      verticalHelp: "Vitres côte à côte",
      horizontal: "Horizontal",
      horizontalHelp: "Vitres superposées",
      count: "Choisissez le nombre",
      sections: "sections",
      chooseDirection: "Choisir vertical ou horizontal",
      result: "{{pane}} deviendra {{count}} thermos {{direction}}.",
      sideBySide: "côte à côte",
      stacked: "superposés",
      dataWarning: "Les mesures et options actuelles de {{pane}} seront effacées.",
      create: "Créer {{count}} sections",
      createAndErase: "Créer {{count}} sections et effacer les données",
      maximum: "Cette division créerait {{total}} thermos; maximum {{max}}.",
      created: "{{count}} sections créées dans {{code}} · {{pane}}.",
    },
    incomplete: {
      kicker: "Mesures incomplètes",
      title: "{{code}} · {{name}} n’est pas terminée",
      message: "Il reste {{missing}} thermos à mesurer sur {{total}}.",
      complete: "Compléter les mesures",
      addAnyway: "Ajouter quand même",
    },
  },
  history: {
    groupAria: "Historique des modifications",
    undo: "Annuler la dernière modification",
    undoShort: "Annuler",
    redo: "Rétablir la dernière modification",
    redoShort: "Rétablir",
    undone: "Dernière modification annulée.",
    redone: "Dernière modification rétablie.",
    waitForPhoto: "Attendez la fin de l’analyse de la photo.",
  },
  autosave: {
    unsaved: "Modifications non enregistrées",
    saving: "Enregistrement…",
    saved: "Enregistré",
    savedAt: "Enregistré à {{time}}",
    failed: "Échec de l’enregistrement",
    failedHelp: "Vos changements sont encore dans cet appareil. Réessayez avant de fermer.",
    retrying: "Nouvelle tentative…",
    offline: "Hors ligne · en attente de connexion",
    restored: "Brouillon restauré.",
    leaveWarning: "Des mesures ne sont pas encore enregistrées. Voulez-vous vraiment quitter?",
  },
  validation: {
    clientAction: "Envoyer mes mesures",
    technicianAction: "Valider les mesures finales",
    adminAction: "Marquer les mesures reçues",
    phoneAction: "Confirmer les mesures téléphone",
    validating: "Validation…",
    flushAutosave: "Enregistrement des derniers changements…",
    incompleteTitle: "Mesures incomplètes",
    incompleteDossier: "Remplissez les mesures manquantes avant de continuer.",
    missingPane: "{{window}}, thermos {{pane}} : {{fields}} requis.",
    photoBusy: "Attendez la fin de l’analyse de la photo avant de valider.",
    clientSuccess: "Mesures envoyées à Vosthermos. Merci!",
    technicianSuccess: "Mesures finales validées.",
    adminSuccess: "Mesures marquées comme reçues.",
    alreadySubmitted: "Ces mesures ont déjà été envoyées.",
    failed: "Les mesures n’ont pas pu être validées.",
    finalWarning: "La validation confirme que ces mesures sont finales et prêtes pour la prochaine étape.",
  },
  tutorial: {
    launcher: "Tutoriel",
    openAria: "Ouvrir le tutoriel de prise de mesures",
    promptKicker: "Besoin d’aide?",
    promptTitle: "Voulez-vous voir comment ça fonctionne?",
    promptBody: "Une courte démonstration vous montre comment choisir la fenêtre, entrer les mesures et valider le dossier.",
    promptDuration: "Environ 1 minute",
    start: "Voir le tutoriel",
    skip: "Pas maintenant",
    kicker: "Démonstration réelle",
    title: "Mesurer une fenêtre",
    duration: "Environ 1 min",
    step: "Étape",
    of: "sur",
    previous: "Précédent",
    next: "Suivant",
    pause: "Pause",
    resume: "Reprendre",
    replay: "Rejouer",
    finish: "Fermer",
    close: "Fermer le tutoriel",
    loading: "Préparation de la démonstration…",
    isolated: "Cette démonstration est isolée : elle ne modifie jamais le dossier du client.",
    steps: [
      { title: "Choisissez la fenêtre", body: "Ouvrez la liste des modèles et choisissez la disposition qui ressemble à la fenêtre.", tip: "Vous pouvez aussi prendre une photo bien de face." },
      { title: "Sélectionnez un thermos", body: "Touchez T1, T2 ou un autre thermos. Le formulaire suit toujours celui qui est sélectionné.", tip: "Le thermos sélectionné est clairement mis en évidence." },
      { title: "Entrez les mesures", body: "Inscrivez largeur, hauteur et épaisseur dans l’unité de votre choix.", tip: "Les pouces restent l’unité de production; mm et cm sont convertis automatiquement." },
      { title: "Divisez seulement au besoin", body: "Utilisez Modifier le thermos pour créer des sections verticales ou horizontales.", tip: "Les poignées permettent ensuite d’ajuster les proportions." },
      { title: "Ajoutez les options", body: "Indiquez Low-E, Argon, vitrage, intercalaire, accès et carreaux décoratifs.", tip: "Choisissez Je ne sais pas / Inconnu lorsque nécessaire." },
      { title: "Ajoutez les autres fenêtres", body: "Le gros bouton plus crée un nouveau plan avec son propre numéro F.", tip: "Terminez une fenêtre à la fois pour garder les thermos bien identifiés." },
      { title: "Annulez, rétablissez ou validez", body: "Corrigez les dernières actions au besoin, puis confirmez la fin de la prise de mesures.", tip: "La sauvegarde automatique protège le brouillon pendant le travail." },
    ],
  },
  help: {
    kicker: "Aide rapide",
    trigger: "Ouvrir l’aide",
    close: "Fermer l’aide",
    plan: {
      title: "Utiliser le plan",
      body: "Touchez un thermos (T1, T2…) pour le sélectionner. Faites glisser les flèches sur les séparations pour ajuster les proportions. Le dessin sert à identifier les thermos; il n’est pas à l’échelle.",
    },
    photo: {
      title: "À quoi sert la photo?",
      body: "Prenez la fenêtre bien de face. La photo détecte les divisions et reste jointe au dossier, à côté du modèle dans le rapport admin. Elle n’apparaît jamais derrière le dessin et ne remplace pas les mesures.",
    },
    measurements: {
      title: "Quoi mesurer?",
      body: "Chaque T1, T2… représente un thermos, soit une unité de vitrage scellée. Entrez les dimensions de ce thermos, pas celles du cadre complet. L’épaisseur correspond à l’unité complète.",
    },
    options: {
      title: "Comprendre les options",
      body: "Ces choix décrivent seulement le thermos sélectionné.",
      items: [
        { label: "Low-E", body: "Couche qui réduit les pertes de chaleur." },
        { label: "Argon", body: "Gaz isolant entre les vitres." },
        { label: "Trempé", body: "Verre de sécurité traité." },
        { label: "Laminé", body: "Verre retenu par une pellicule." },
        { label: "Intercalaire", body: "Barre au pourtour qui sépare les vitres." },
        { label: "Vitrage", body: "Nombre de feuilles de verre." },
        { label: "Accès", body: "Indique si une échelle est nécessaire pour atteindre le thermos." },
      ],
    },
    finalization: {
      title: "Annuler, rétablir ou valider?",
      body: "Annuler revient sur la dernière modification. Rétablir la remet. Valider confirme que toutes les mesures requises sont prêtes pour la prochaine étape.",
    },
  },
};

const en = {
  locale: "en",
  documentTitle: "Window measurements | Vosthermos",
  brandAlt: "Vosthermos",
  common: {
    close: "Close",
    cancel: "Cancel",
    continue: "Continue",
    back: "Back",
    confirm: "Confirm",
    retry: "Try again",
    yes: "Yes",
    no: "No",
    unknown: "I don’t know / Unknown",
    choose: "Choose",
    optional: "Optional",
  },
  modes: {
    client: "Client measurements",
    technician: "Final measurements",
    admin: "Measurement file",
    phone: "Phone measurements",
    approximate: "Pre-quote",
  },
  loading: {
    dossier: "Opening your file…",
    unavailableTitle: "Link unavailable",
    unavailableBody: "Contact Vosthermos to receive a new link.",
    alreadyReceivedTitle: "Measurements received",
    alreadyReceivedBody: "Our team can now prepare your quote.",
  },
  progress: {
    title: "Measurement steps",
    measured: "measured",
    summary: "{{complete}} / {{total}} measured",
    windowSummary: "{{complete}} of {{total}} glass units measured in {{window}}",
    dossierSummary: "{{complete}} of {{total}} glass units measured in this file",
    paneComplete: "Measured",
    paneInProgress: "Measurements in progress",
    paneEmpty: "To measure",
    paneMissing: "Measurements required",
    allComplete: "All measurements are complete",
  },
  windows: {
    title: "Windows",
    defaultName: "Window {{number}}",
    firstDefaultName: "Living room",
    count: "{{count}} window(s)",
    thermosCount: "{{count}} glass unit(s)",
    add: "Add another window",
    addHelp: "Create a new glazing plan",
    rename: "Rename window",
    renameAria: "Rename {{code}} · {{name}}",
    nameField: "Room or window name",
    namePlaceholder: "e.g. Living room",
    nameRequired: "Enter a name for this window.",
    added: "{{code}} added.",
    renamed: "{{code}} renamed “{{name}}”.",
    selectedAria: "Open {{code}} · {{name}}",
  },
  models: {
    toolbarAria: "Choose a window type or take a photo",
    chooseType: "Choose a window type",
    selection: "Selected:",
    quickConfigurations: "Quick configurations",
    menuAria: "Window types",
    custom: "Custom layout",
    customSummary: "Custom layout · {{count}} glass unit(s)",
    gridSummary: "{{columns}} column(s) × {{rows}} row(s) · {{count}} glass unit(s)",
    currentAlreadyApplied: "The “{{label}}” layout is already applied.",
    changeConfirmation: "Changing the layout will erase the measurements for {{code}}. Continue?",
    created: "“{{label}}” layout created. {{count}} glass unit(s) to measure.",
    detected: "Detected layout: {{label}}.",
  },
  photo: {
    take: "Take a photo",
    retake: "Retake the photo",
    inputAria: "Take a photo of the window",
    detectedAutomatically: "Divisions are detected automatically",
    analyzing: "Analyzing photo…",
    analyzingHelp: "The drawing is created automatically",
    analyzingMessage: "Analyzing the photo automatically…",
    replaceHelp: "A new photo will replace this analysis",
    invalid: "Choose a valid window photo.",
    uploading: "Uploading photo…",
    uploaded: "Photo added to the file.",
    applied: "Photo analyzed · “{{label}}” layout applied.",
    retained: "Photo saved · drawing unchanged.",
    failed: "Photo saved. The divisions were not recognized: retake it straight on or choose a type.",
    uploadFailed: "The photo could not be uploaded.",
    analysisFailed: "The photo was saved, but automatic analysis failed.",
    analysisLimit: "The automatic analysis limit has been reached. Correct the drawing manually.",
    linked: "Photo linked to this window.",
    adminPreview: "Reference photo",
    adminPreviewAlt: "Photo of {{code}} · {{name}}",
  },
  canvas: {
    aria: "Interactive window drawing",
    tapToSelect: "Tap to select",
    editing: "You are editing",
    selectedLabel: "{{code}}, glass unit {{pane}}. You are editing this glass unit.",
    availableLabel: "{{code}}, glass unit {{pane}}. Select this glass unit.",
    editSelected: "Edit selected glass unit",
    editSelectedHelp: "Split vertically or horizontally",
    noSelection: "No glass unit selected",
    selectedThermos: "Selected glass unit",
    dividerAria: "{{axis}} divider {{index}}",
    dividerLinked: ", continues across all rows",
    dividerVerticalTitle: "Drag left or right",
    dividerHorizontalTitle: "Drag up or down",
    equalize: "Distribute equally",
    equalized: "All dividers in {{code}} were distributed equally.",
    reset: "Reset drawing",
    resetConfirmation: "Reset only {{code}} and its measurements?",
    resetDone: "{{code}} was reset.",
    maximumReached: "Maximum of {{max}} glass units reached in {{code}}.",
  },
  measurements: {
    title: "Measurements",
    unit: "Unit",
    unitChanged: "Measurement unit: {{unit}}.",
    units: { in: "in", mm: "mm", cm: "cm" },
    width: "Width",
    height: "Height",
    thickness: "Thickness",
    fraction: "{{dimension}} fraction",
    widthPlaceholder: "e.g. 32",
    heightPlaceholder: "e.g. 48",
    thicknessPlaceholder: "e.g. 1",
    required: "Required",
    clientThicknessOptional: "Optional for a pre-quote; required before ordering.",
    invalid: "Enter a valid measurement.",
    maximum: "Maximum {{value}} {{unit}}.",
    widthHeightRequired: "Width and height are required.",
    finalDimensionsRequired: "Width, height and thickness are required for final measurements.",
  },
  options: {
    title: "Glass unit options",
    lowE: "Low-E",
    argon: "Argon",
    tempered: "Tempered",
    laminated: "Laminated",
    spacer: "Spacer",
    glazing: "Glazing",
    access: "Access",
    notes: "Special notes",
    notesPlaceholder: "Shape, defect, access, special details…",
    spacerChoices: {
      empty: "Choose",
      unknown: "I don’t know / Unknown",
      black: "Black",
      gray: "Gray",
      white: "White",
      stainless: "Stainless steel",
    },
    glazingChoices: {
      empty: "Choose",
      unknown: "I don’t know / Unknown",
      double: "Double",
      triple: "Triple",
      single: "Single",
    },
    accessChoices: {
      empty: "Choose",
      withLadder: "With ladder",
      withoutLadder: "Without ladder",
    },
    decorative: {
      title: "Decorative grilles",
      help: "Add grille lines without creating new glass units",
      instruction: "Choose the number of grille lines in this glass unit only.",
      vertical: "Vertical",
      horizontal: "Horizontal",
      addVertical: "Add one vertical line",
      removeVertical: "Remove one vertical line",
      addHorizontal: "Add one horizontal line",
      removeHorizontal: "Remove one horizontal line",
    },
  },
  modals: {
    rename: {
      title: "Rename window",
      save: "Save",
    },
    split: {
      title: "Split this glass unit",
      intro: "Create 2 to 4 glass units in the selected section.",
      optionsAria: "Division options",
      direction: "Choose the direction",
      vertical: "Vertical",
      verticalHelp: "Panes side by side",
      horizontal: "Horizontal",
      horizontalHelp: "Panes stacked",
      count: "Choose the number",
      sections: "sections",
      chooseDirection: "Choose vertical or horizontal",
      result: "{{pane}} will become {{count}} glass units {{direction}}.",
      sideBySide: "side by side",
      stacked: "stacked",
      dataWarning: "The current measurements and options for {{pane}} will be erased.",
      create: "Create {{count}} sections",
      createAndErase: "Create {{count}} sections and erase data",
      maximum: "This division would create {{total}} glass units; maximum {{max}}.",
      created: "{{count}} sections created in {{code}} · {{pane}}.",
    },
    incomplete: {
      kicker: "Incomplete measurements",
      title: "{{code}} · {{name}} is not complete",
      message: "There are {{missing}} glass units left to measure out of {{total}}.",
      complete: "Complete measurements",
      addAnyway: "Add anyway",
    },
  },
  history: {
    groupAria: "Change history",
    undo: "Undo the last change",
    undoShort: "Undo",
    redo: "Redo the last change",
    redoShort: "Redo",
    undone: "Last change undone.",
    redone: "Last change restored.",
    waitForPhoto: "Wait until the photo analysis is complete.",
  },
  autosave: {
    unsaved: "Unsaved changes",
    saving: "Saving…",
    saved: "Saved",
    savedAt: "Saved at {{time}}",
    failed: "Save failed",
    failedHelp: "Your changes are still on this device. Try again before closing.",
    retrying: "Trying again…",
    offline: "Offline · waiting for a connection",
    restored: "Draft restored.",
    leaveWarning: "Some measurements have not been saved yet. Do you really want to leave?",
  },
  validation: {
    clientAction: "Send my measurements",
    technicianAction: "Confirm final measurements",
    adminAction: "Mark measurements as received",
    phoneAction: "Confirm phone measurements",
    validating: "Confirming…",
    flushAutosave: "Saving the latest changes…",
    incompleteTitle: "Incomplete measurements",
    incompleteDossier: "Complete the missing measurements before continuing.",
    missingPane: "{{window}}, glass unit {{pane}}: {{fields}} required.",
    photoBusy: "Wait until the photo analysis is complete before confirming.",
    clientSuccess: "Measurements sent to Vosthermos. Thank you!",
    technicianSuccess: "Final measurements confirmed.",
    adminSuccess: "Measurements marked as received.",
    alreadySubmitted: "These measurements have already been sent.",
    failed: "The measurements could not be confirmed.",
    finalWarning: "Confirmation marks these measurements as final and ready for the next step.",
  },
  tutorial: {
    launcher: "Tutorial",
    openAria: "Open the measurement tutorial",
    promptKicker: "Need help?",
    promptTitle: "Would you like to see how it works?",
    promptBody: "A short demonstration shows you how to choose the window, enter measurements and confirm the file.",
    promptDuration: "About 1 minute",
    start: "View tutorial",
    skip: "Not now",
    kicker: "Live demonstration",
    title: "Measure a window",
    duration: "About 1 min",
    step: "Step",
    of: "of",
    previous: "Previous",
    next: "Next",
    pause: "Pause",
    resume: "Resume",
    replay: "Replay",
    finish: "Close",
    close: "Close tutorial",
    loading: "Preparing the demonstration…",
    isolated: "This demonstration is isolated: it never changes the client file.",
    steps: [
      { title: "Choose the window", body: "Open the model list and choose the layout that looks like the window.", tip: "You can also take a straight-on photo." },
      { title: "Select a glass unit", body: "Tap T1, T2 or another glass unit. The form always follows the selected unit.", tip: "The selected glass unit is clearly highlighted." },
      { title: "Enter the measurements", body: "Enter width, height and thickness in your preferred unit.", tip: "Inches remain the production unit; mm and cm are converted automatically." },
      { title: "Split only when needed", body: "Use Edit glass unit to create vertical or horizontal sections.", tip: "The handles then let you adjust the proportions." },
      { title: "Add the options", body: "Choose Low-E, Argon, glazing, spacer, access and decorative grilles.", tip: "Choose I don’t know / Unknown when needed." },
      { title: "Add the other windows", body: "The large plus button creates a new plan with its own F number.", tip: "Finish one window at a time to keep every glass unit properly identified." },
      { title: "Undo, redo or confirm", body: "Correct recent actions if needed, then confirm the end of the measurement process.", tip: "Automatic saving protects the draft while you work." },
    ],
  },
  help: {
    kicker: "Quick help",
    trigger: "Open help",
    close: "Close help",
    plan: {
      title: "Using the plan",
      body: "Tap a glass unit (T1, T2…) to select it. Drag the arrows on a divider to adjust the proportions. The drawing identifies each unit; it is not to scale.",
    },
    photo: {
      title: "What is the photo used for?",
      body: "Take the photo straight on. It detects the divisions and stays attached to the file, beside the model in the admin report. It never appears behind the drawing and does not replace the measurements.",
    },
    measurements: {
      title: "What should I measure?",
      body: "Each T1, T2… represents one sealed glass unit. Enter that unit’s dimensions, not the full frame. Thickness means the complete sealed unit.",
    },
    options: {
      title: "Understanding the options",
      body: "These choices describe the selected glass unit only.",
      items: [
        { label: "Low-E", body: "Coating that reduces heat loss." },
        { label: "Argon", body: "Insulating gas between the panes." },
        { label: "Tempered", body: "Heat-treated safety glass." },
        { label: "Laminated", body: "Glass held together by an interlayer." },
        { label: "Spacer", body: "Perimeter bar separating the panes." },
        { label: "Glazing", body: "Number of glass panes." },
        { label: "Access", body: "Indicates whether a ladder is required to reach the glass unit." },
      ],
    },
    finalization: {
      title: "Undo, redo or confirm?",
      body: "Undo reverses the latest change. Redo restores it. Confirm marks all required measurements as ready for the next step.",
    },
  },
};

export const MEASUREMENT_COPY = { fr, en };

export function normalizeMeasurementLocale(locale) {
  return String(locale || "fr").toLowerCase().startsWith("en") ? "en" : "fr";
}

export function getMeasurementCopy(locale = "fr") {
  return MEASUREMENT_COPY[normalizeMeasurementLocale(locale)];
}

export function formatMeasurementCopy(template, variables = {}) {
  return String(template ?? "").replace(/\{\{(\w+)\}\}/g, (match, key) => (
    Object.prototype.hasOwnProperty.call(variables, key) ? String(variables[key]) : match
  ));
}

export default MEASUREMENT_COPY;
