import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAdmin } from "@/lib/admin-auth";
import fs from "fs";
import path from "path";
import { spawn } from "child_process";
import { COMPANY_INFO } from "@/lib/company-info";

export const dynamic = "force-dynamic";

const KEY_MAP = {
  company_legal_name: "legalName",
  company_neq: "neq",
  company_address: "address",
  company_city: "city",
  company_province: "province",
  company_postal_code: "postalCode",
  company_phone: "phone",
  company_email: "email",
  company_web: "web",
  rbq_number: "rbqNumber",
};

function toTelFormat(phone) {
  const digits = String(phone || "").replace(/\D/g, "");
  if (digits.length === 10) return `+1${digits}`;
  if (digits.length === 11 && digits.startsWith("1")) return `+${digits}`;
  return phone || COMPANY_INFO.phoneTel;
}

function esc(v) { return String(v || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"'); }

function buildFileContent(values) {
  const v = values;
  return `// Client-safe constant with default company NAP.
// Auto-generated by /api/admin/company/sync — edit via /admin/parametres then sync.
// DO NOT EDIT BY HAND (changes will be overwritten on next sync).

export const COMPANY_INFO = {
  legalName: "${esc(v.legalName || COMPANY_INFO.legalName || "Vosthermos")}",
  neq: "${esc(v.neq || "")}",
  address: "${esc(v.address || COMPANY_INFO.address)}",
  city: "${esc(v.city || COMPANY_INFO.city)}",
  cityShort: "${esc((v.city || COMPANY_INFO.city).split(",")[0].split("-de-")[0])}",
  province: "${esc(v.province || COMPANY_INFO.province)}",
  postalCode: "${esc(v.postalCode || COMPANY_INFO.postalCode)}",
  phone: "${esc(v.phone || COMPANY_INFO.phone)}",
  phoneTel: "${esc(toTelFormat(v.phone))}",
  email: "${esc(v.email || COMPANY_INFO.email)}",
  web: "${esc(v.web || COMPANY_INFO.web)}",
  url: "https://www.${esc(v.web || COMPANY_INFO.web)}",
  rbqNumber: "${esc(v.rbqNumber || COMPANY_INFO.rbqNumber)}",
  facebook: "https://www.facebook.com/profile.php?id=61562303553558",
  instagram: "https://instagram.com/vosthermos/",
  logo: "https://www.vosthermos.com/images/Vos-Thermos-Logo.png",
};
`;
}

function updatePublicAiFiles(values) {
  const phone = values.phone || COMPANY_INFO.phone;
  const files = [
    path.join(process.cwd(), "public", "llms.txt"),
    path.join(process.cwd(), "public", "llms-full.txt"),
  ];

  for (const file of files) {
    if (!fs.existsSync(file)) continue;
    let text = fs.readFileSync(file, "utf8");
    text = text.replace(/^- Phone: .*$/gm, `- Phone: ${phone}`);
    text = text.replace(/\bCall [0-9][0-9().\-\s]+ or fill/g, `Call ${phone} or fill`);
    fs.writeFileSync(file, text, "utf8");
  }
}

async function updateStoredPhoneReferences(values) {
  const phone = values.phone || COMPANY_INFO.phone;
  const oldPhones = [...new Set([COMPANY_INFO.phone, "514-825-8411"].filter(Boolean).filter((p) => p !== phone))];
  let updated = 0;

  for (const oldPhone of oldPhones) {
    updated += await prisma.$executeRawUnsafe(
      `UPDATE blog_posts
       SET content = REPLACE(content, $1, $2),
           excerpt = REPLACE(excerpt, $1, $2)
       WHERE content LIKE '%' || $1 || '%' OR excerpt LIKE '%' || $1 || '%'`,
      oldPhone,
      phone,
    );
    updated += await prisma.$executeRawUnsafe(
      `UPDATE products
       SET description = REPLACE(description, $1, $2),
           "descriptionEn" = REPLACE("descriptionEn", $1, $2),
           "detailedDescription" = REPLACE("detailedDescription", $1, $2),
           "detailedDescriptionEn" = REPLACE("detailedDescriptionEn", $1, $2)
       WHERE description LIKE '%' || $1 || '%'
          OR "descriptionEn" LIKE '%' || $1 || '%'
          OR "detailedDescription" LIKE '%' || $1 || '%'
          OR "detailedDescriptionEn" LIKE '%' || $1 || '%'`,
      oldPhone,
      phone,
    );
  }

  return updated;
}

async function runCommand(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd: process.cwd(), ...opts });
    let stdout = "", stderr = "";
    child.stdout?.on("data", (d) => (stdout += d));
    child.stderr?.on("data", (d) => (stderr += d));
    child.on("close", (code) => resolve({ code, stdout, stderr }));
    child.on("error", (e) => resolve({ code: -1, stdout, stderr: e.message }));
  });
}

export async function POST() {
  try { await requireAdmin(); }
  catch { return NextResponse.json({ error: "Non autorise" }, { status: 401 }); }

  try {
    // 1. Read settings from DB
    const rows = await prisma.$queryRawUnsafe(
      `SELECT key, value FROM site_settings WHERE key = ANY($1)`,
      Object.keys(KEY_MAP),
    );
    const values = {};
    for (const r of rows) values[KEY_MAP[r.key]] = r.value;

    // 2. Generate new file content
    const content = buildFileContent(values);

    // 3. Write to src/lib/company-info.js
    const filePath = path.join(process.cwd(), "src", "lib", "company-info.js");
    fs.writeFileSync(filePath, content, "utf8");
    updatePublicAiFiles(values);
    const storedTextUpdated = await updateStoredPhoneReferences(values);

    // 4. Git commit + push (best-effort, don't block response)
    const gitSteps = [];
    const add = await runCommand("git", ["add", "src/lib/company-info.js", "public/llms.txt", "public/llms-full.txt"]);
    gitSteps.push({ step: "add", code: add.code });

    if (add.code === 0) {
      const commit = await runCommand("git", [
        "commit", "-m", "chore(company): auto-sync company-info.js from DB settings",
      ]);
      gitSteps.push({ step: "commit", code: commit.code, message: commit.stdout || commit.stderr });
      if (commit.code === 0) {
        const push = await runCommand("git", ["push", "origin", "master"]);
        gitSteps.push({ step: "push", code: push.code, message: push.stdout || push.stderr });
      }
    }

    // 5. Trigger rebuild in background (detached)
    let rebuildTriggered = false;
    try {
      const rebuild = spawn(
        "sh",
        ["-c", "pm2 stop vosthermos && rm -rf .next && npm run build && pm2 start vosthermos"],
        { cwd: process.cwd(), detached: true, stdio: "ignore" },
      );
      rebuild.unref();
      rebuildTriggered = true;
    } catch (e) {
      gitSteps.push({ step: "rebuild", error: e.message });
    }

    return NextResponse.json({
      ok: true,
      values,
      gitSteps,
      rebuildTriggered,
      storedTextUpdated,
      message: rebuildTriggered
        ? "Synchronisation lancee. Le site sera reconstruit dans ~2 minutes."
        : "Fichier mis a jour mais rebuild n'a pas pu etre declenche. Redeployez manuellement.",
    });
  } catch (err) {
    return NextResponse.json({ error: err.message || "Erreur sync" }, { status: 500 });
  }
}
