import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { requireAdmin } from "@/lib/admin-auth";
import fs from "fs";
import path from "path";
import { spawn } from "child_process";

export const dynamic = "force-dynamic";

const KEY_MAP = {
  company_legal_name: "legalName",
  company_neq: "neq",
  company_address: "address",
  company_city: "city",
  company_province: "province",
  company_postal_code: "postalCode",
  company_phone: "phone",
  company_email: "email",
  company_web: "web",
};

function toTelFormat(phone) {
  const digits = String(phone || "").replace(/\D/g, "");
  if (digits.length === 10) return `+1${digits}`;
  if (digits.length === 11 && digits.startsWith("1")) return `+${digits}`;
  return phone || "+15148258411";
}

function esc(v) { return String(v || "").replace(/\\/g, "\\\\").replace(/"/g, '\\"'); }

function buildFileContent(values) {
  const v = values;
  return `// Client-safe constant with default company NAP.
// Auto-generated by /api/admin/company/sync — edit via /admin/parametres then sync.
// DO NOT EDIT BY HAND (changes will be overwritten on next sync).

export const COMPANY_INFO = {
  legalName: "${esc(v.legalName || "Vosthermos")}",
  neq: "${esc(v.neq || "")}",
  address: "${esc(v.address || "330 Ch. St-Francois-Xavier, Local 104")}",
  city: "${esc(v.city || "Saint-Francois-Xavier-de-Brompton")}",
  cityShort: "${esc((v.city || "Saint-Francois-Xavier-de-Brompton").split(",")[0].split("-de-")[0])}",
  province: "${esc(v.province || "QC")}",
  postalCode: "${esc(v.postalCode || "J5B 1C9")}",
  phone: "${esc(v.phone || "514-825-8411")}",
  phoneTel: "${esc(toTelFormat(v.phone))}",
  email: "${esc(v.email || "info@vosthermos.com")}",
  web: "${esc(v.web || "vosthermos.com")}",
  url: "https://www.${esc(v.web || "vosthermos.com")}",
  facebook: "https://www.facebook.com/profile.php?id=61562303553558",
  instagram: "https://instagram.com/vosthermos/",
  logo: "https://www.vosthermos.com/images/Vos-Thermos-Logo.png",
};
`;
}

async function runCommand(cmd, args, opts = {}) {
  return new Promise((resolve) => {
    const child = spawn(cmd, args, { cwd: process.cwd(), ...opts });
    let stdout = "", stderr = "";
    child.stdout?.on("data", (d) => (stdout += d));
    child.stderr?.on("data", (d) => (stderr += d));
    child.on("close", (code) => resolve({ code, stdout, stderr }));
    child.on("error", (e) => resolve({ code: -1, stdout, stderr: e.message }));
  });
}

export async function POST() {
  try { await requireAdmin(); }
  catch { return NextResponse.json({ error: "Non autorise" }, { status: 401 }); }

  try {
    // 1. Read settings from DB
    const rows = await prisma.$queryRawUnsafe(
      `SELECT key, value FROM site_settings WHERE key = ANY($1)`,
      Object.keys(KEY_MAP),
    );
    const values = {};
    for (const r of rows) values[KEY_MAP[r.key]] = r.value;

    // 2. Generate new file content
    const content = buildFileContent(values);

    // 3. Write to src/lib/company-info.js
    const filePath = path.join(process.cwd(), "src", "lib", "company-info.js");
    fs.writeFileSync(filePath, content, "utf8");

    // 4. Git commit + push (best-effort, don't block response)
    const gitSteps = [];
    const add = await runCommand("git", ["add", "src/lib/company-info.js"]);
    gitSteps.push({ step: "add", code: add.code });

    if (add.code === 0) {
      const commit = await runCommand("git", [
        "commit", "-m", "chore(company): auto-sync company-info.js from DB settings",
      ]);
      gitSteps.push({ step: "commit", code: commit.code, message: commit.stdout || commit.stderr });
      if (commit.code === 0) {
        const push = await runCommand("git", ["push", "origin", "master"]);
        gitSteps.push({ step: "push", code: push.code, message: push.stdout || push.stderr });
      }
    }

    // 5. Trigger rebuild in background (detached)
    let rebuildTriggered = false;
    try {
      const rebuild = spawn(
        "sh",
        ["-c", "pm2 stop vosthermos && rm -rf .next && npm run build && pm2 start vosthermos"],
        { cwd: process.cwd(), detached: true, stdio: "ignore" },
      );
      rebuild.unref();
      rebuildTriggered = true;
    } catch (e) {
      gitSteps.push({ step: "rebuild", error: e.message });
    }

    return NextResponse.json({
      ok: true,
      values,
      gitSteps,
      rebuildTriggered,
      message: rebuildTriggered
        ? "Synchronisation lancee. Le site sera reconstruit dans ~2 minutes."
        : "Fichier mis a jour mais rebuild n'a pas pu etre declenche. Redeployez manuellement.",
    });
  } catch (err) {
    return NextResponse.json({ error: err.message || "Erreur sync" }, { status: 500 });
  }
}
